supertokens/docs

static/scripts/commonDocsBuilder.js, static/style/commonDocs.css
css changes:
- search box:
- border radius: 6px
- font-famiy: Rubik
- font-style: normal(non-italic) 
- background-colour: #363636
- placefholder-text color: #dddddd, weight: 16px
- Dropdown menu:
- Heading:
- line-height:24px
- font-weight:bold
- background: #363636
- opacity: 40%
- Result(below heading) 
- line height: 21px
- Left-Subcategory:
- color #dddddd
- font-weight: normal
- Righ-Subcategory:
- color #ffffff
- font-weight: medium
text-highllight:#ff9933
=> With docsearch

nodejs/docs/emailverification/override/apis.md, nodejs/docs/emailverification/override/functions.md
emailverification recipe docs related to overriding apis and functions updated for nodejs
=> …emailverification recipe docs (nodejs)

community/docs/introduction.md, community/website/pages/en/versions.js, community/website/versioned_docs/version-3.4.X/introduction.md, static/scripts/commonDocsBuilder.js
Related to https://github.com/supertokens/docs/issues/44
=> Remove old docs and old core deployment

v2/session/introduction.mdx
Fix typo in session recipe Feature page
=> Fix Typo in Session recipe docs

v2/.github/workflows/github-actions-netlify.yml
=> adds netlify action PR

v2/emailpassword/common-customizations/user-roles/assigning-session-roles.mdx
Simple change of adding a closing quote to a code sample.
N/A
None
=> Update assigning-session-roles.mdx by adding closing quotation mark

v2/nodejs/emailpassword/override/functions.mdx, v2/nodejs/emailpassword/updateemailorpassword.mdx, v2/nodejs/emailverification/override/functions.mdx, v2/nodejs/emailverification/revokeemailverificationtokens.mdx, v2/nodejs/emailverification/unverifyemail.mdx, v2/nodejs/installation.mdx, v2/nodejs/sidebars.js, v2/nodejs/thirdparty/getusersbyemail.mdx, v2/nodejs/thirdparty/override/functions.mdx, v2/nodejs/thirdpartyemailpassword/override/functions.mdx
- Adds nodejs recipe functions to get users by email in thirdparty and thirdpartyemailpassword
- Adds nodejs recipe functions for updating user's email or password
- Adds nodejs recipe functions for emailverification
- https://github.com/supertokens/supertokens-core/issues/277
- https://github.com/supertokens/supertokens-core/issues/275
- https://github.com/supertokens/supertokens-core/issues/270
=> adds docs for missing recipe functions

v2/emailpassword/common-customizations/sessions/change-session-timeout.mdx, v2/emailpassword/nextjs/session-verification/in-api.mdx, v2/session/common-customizations/sessions/change-session-timeout.mdx, v2/thirdparty/common-customizations/sessions/change-session-timeout.mdx, v2/thirdparty/nextjs/session-verification/in-api.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/change-session-timeout.mdx, v2/thirdpartyemailpassword/nextjs/session-verification/in-api.mdx
Fixs broken links linking to access token blacklisting and session object
- none
- none
=> fixs broken links

v2/emailpassword/common-customizations/styling/changing-style.mdx, v2/thirdparty/common-customizations/styling/changing-style.mdx, v2/thirdpartyemailpassword/common-customizations/styling/changing-style.mdx
Added documentation for an extra property passed to `SuperTokens.init` that applies styling to all components.
- supertokens/supertokens-auth-react#312
=> Added documentation for adding styles that apply across recipes

v2/emailpassword/common-customizations/styling/changing-style.mdx, v2/thirdparty/common-customizations/styling/changing-style.mdx, v2/thirdpartyemailpassword/common-customizations/styling/changing-style.mdx
Added a section into styling about overriding the font
- supertokens/supertokens-auth-react#303
=> Added a section into styling about overriding the font

v2/session/advanced-customizations/frontend-hooks/handle-event.mdx, v2/session/common-customizations/sessions/handling-session-expiry.mdx
Added a few lines about sessionExpiredOrRevoked wherever I found reference to the UNAUTHORISED event
- supertokens/supertokens-website#73
=> Documented sessionExpiredOrRevoked on UNAUTHORISED events

v2/emailpassword/common-customizations/email-verification/changing-token-lifetime.mdx, v2/emailpassword/common-customizations/reset-password/changing-token-lifetime.mdx, v2/emailpassword/sidebars.js, v2/thirdparty/common-customizations/email-verification/changing-token-lifetime.mdx, v2/thirdparty/sidebars.js, v2/thirdpartyemailpassword/common-customizations/email-verification/changing-token-lifetime.mdx, v2/thirdpartyemailpassword/common-customizations/reset-password/changing-token-lifetime.mdx, v2/thirdpartyemailpassword/sidebars.js
Adds docs for changing of reset password and email verification link's lifetime
- https://github.com/supertokens/supertokens-core/issues/297
=> Changing of password and email verification link's lifetime

v2/emailpassword/serverless/with-aws-lambda/appsync-integration.mdx, v2/emailpassword/serverless/with-aws-lambda/authorizer.mdx, v2/emailpassword/sidebars.js, v2/session/serverless/with-aws-lambda/appsync-integration.mdx, v2/session/serverless/with-aws-lambda/authorizer.mdx, v2/session/sidebars.js, v2/thirdparty/serverless/with-aws-lambda/appsync-integration.mdx, v2/thirdparty/serverless/with-aws-lambda/authorizer.mdx, v2/thirdparty/sidebars.js, v2/thirdpartyemailpassword/serverless/with-aws-lambda/appsync-integration.mdx, v2/thirdpartyemailpassword/serverless/with-aws-lambda/authorizer.mdx, v2/thirdpartyemailpassword/sidebars.js
Added a guide that shows how to integrate SuperTokens with AWS AppSync
-
=> Adding a guide to integrate SuperTokens with AWS AppSync

v2/emailpassword/serverless/with-aws-lambda/appsync-integration.mdx, v2/emailpassword/serverless/with-aws-lambda/authorizer.mdx, v2/session/serverless/with-aws-lambda/appsync-integration.mdx, v2/session/serverless/with-aws-lambda/authorizer.mdx, v2/thirdparty/serverless/with-aws-lambda/appsync-integration.mdx, v2/thirdparty/serverless/with-aws-lambda/authorizer.mdx, v2/thirdpartyemailpassword/serverless/with-aws-lambda/appsync-integration.mdx, v2/thirdpartyemailpassword/serverless/with-aws-lambda/authorizer.mdx
Improved AWS authorizer & AppSync integration docs, fixing the comments on #126 
- #127
=> Improved docs & fixing issues in prev PR

v2/src/components/BackendSDKCasing.tsx, v2/src/theme/Tabs/index.js, v2/thirdpartyemailpassword/quick-setup/backend.mdx
- allows changing casing of variables based on backend sdk currently selected
=> change casing based on backend sdk selected

v2/emailpassword/common-customizations/handling-signin-success.mdx, v2/emailpassword/common-customizations/handling-signup-success.mdx, v2/thirdpartyemailpassword/advanced-customizations/apis-override/disabling.mdx, v2/thirdpartyemailpassword/advanced-customizations/apis-override/usage.mdx, v2/thirdpartyemailpassword/common-customizations/handling-signinup-success.mdx, v2/thirdpartyemailpassword/common-customizations/signup-form/adding-fields.mdx, v2/thirdpartyemailpassword/common-customizations/signup-form/built-in-providers.mdx
- https://github.com/supertokens/supertokens-node/issues/192
=> update to docs to use new tpep interface

v2/emailpassword/nextjs/init.mdx, v2/emailpassword/nextjs/session-verification/in-api.mdx, v2/emailpassword/nextjs/setting-up-backend.mdx, v2/thirdparty/nestjs/guide.mdx, v2/thirdparty/nextjs/init.mdx, v2/thirdparty/nextjs/session-verification/in-api.mdx, v2/thirdparty/nextjs/setting-up-backend.mdx, v2/thirdpartyemailpassword/nextjs/init.mdx, v2/thirdpartyemailpassword/nextjs/session-verification/in-api.mdx, v2/thirdpartyemailpassword/nextjs/setting-up-backend.mdx
Updating NextJS guide to reduce the bundle size of the resulting app.
- supertokens/supertokens-core#178
- supertokens/next.js#3
=> Updated docs to reduce the bundle size of the nextjs app

v2/emailpassword/quick-setup/backend.mdx, v2/session/quick-setup/backend.mdx, v2/thirdparty/quick-setup/backend.mdx, v2/thirdpartyemailpassword/quick-setup/backend.mdx
- added instruction for user to register the `fastify-formbody` plugin.
=> Fastify form data

v2/emailpassword/serverless/with-aws-lambda/auth-serverless.mdx, v2/emailpassword/serverless/with-aws-lambda/session-verification.mdx, v2/emailpassword/serverless/with-netlify/auth-serverless.mdx, v2/emailpassword/serverless/with-netlify/session-verification.mdx, v2/session/serverless/with-aws-lambda/auth-serverless.mdx, v2/session/serverless/with-aws-lambda/session-verification.mdx, v2/session/serverless/with-netlify/auth-serverless.mdx, v2/session/serverless/with-netlify/session-verification.mdx, v2/thirdparty/serverless/with-aws-lambda/auth-serverless.mdx, v2/thirdparty/serverless/with-aws-lambda/session-verification.mdx, v2/thirdparty/serverless/with-netlify/auth-serverless.mdx, v2/thirdparty/serverless/with-netlify/session-verification.mdx, v2/thirdpartyemailpassword/serverless/with-aws-lambda/auth-serverless.mdx, v2/thirdpartyemailpassword/serverless/with-aws-lambda/session-verification.mdx, v2/thirdpartyemailpassword/serverless/with-netlify/auth-serverless.mdx, v2/thirdpartyemailpassword/serverless/with-netlify/session-verification.mdx
Bug fix in AWS Lambda examples.
- https://github.com/supertokens/supertokens-node/issues/196
=> updating aws lambda example for error bug fix

v2/emailpassword/advanced-customizations/apis-override/custom-response.mdx, v2/emailpassword/sidebars.js, v2/session/advanced-customizations/apis-override/custom-response.mdx, v2/session/sidebars.js, v2/thirdparty/advanced-customizations/apis-override/custom-response.mdx, v2/thirdparty/sidebars.js, v2/thirdpartyemailpassword/advanced-customizations/apis-override/custom-response.mdx, v2/thirdpartyemailpassword/sidebars.js
- https://github.com/supertokens/supertokens-node/issues/197
=> Custom response from api

v2/contribute/checklists/website/webflow.md
- Instructions for changing a new file
- Instructions for changing an existing file
=> Overall instructions for changing webflow files

v2/thirdpartyemailpassword/quick-setup/frontend.mdx
Casing bug in docs (Rename React.component -> React.Component)
=> Rename React.component -> React.Component

v2/emailpassword/nestjs/guide.mdx, v2/session/nestjs/guide.mdx, v2/thirdparty/nestjs/guide.mdx, v2/thirdpartyemailpassword/nestjs/guide.mdx
Injection token variable wasn't consistent across docs and overall solution was broken. Same with config filename.
=> [FIX] injection token variable & config filename

v2/emailpassword/common-customizations/delete-user.mdx, v2/emailpassword/sidebars.js, v2/thirdparty/common-customizations/delete-user.mdx, v2/thirdparty/sidebars.js, v2/thirdpartyemailpassword/common-customizations/delete-user.mdx, v2/thirdpartyemailpassword/sidebars.js
Delete user docs
- https://github.com/supertokens/supertokens-core/issues/341
=> adds docs for delete user

v2/thirdparty/common-customizations/sign-in-and-up/custom-providers.mdx, v2/thirdpartyemailpassword/common-customizations/signup-form/custom-providers.mdx
Doc fixs for golang when adding custom providers
=> Golang docs fix

v2/package-lock.json, v2/package.json, v2/src/components/snippetConfigForm/index.tsx, v2/src/components/tsconfig.json, v2/yarn.lock
=> Fixes dependency versions

v2/contribute/checklists/saas/upgrading-users-core-version.md
=> user core version upgrade doc changes

v2/contribute/checklists/website/webflow.md
=> Description on duplicate instances and changes to backend website

v2/contribute/architecture/overview.mdx
Fix an extra 'other' word in overview.mdx file
=> Fix a typo in overview.mdx

v2/passwordless/introduction.mdx, v2/passwordless/quick-setup/backend.mdx, v2/passwordless/quick-setup/frontend.mdx
Un-commented and updated passwordless example links
=> passwordless example changes

v2/auth-react/installation.mdx, v2/auth-react_versioned_docs/version-0.15.X/installation.mdx, v2/community/concepts.mdx, v2/community/migration/to-st.mdx, v2/nodejs/installation.mdx, v2/nodejs_versioned_docs/version-6.0.X/installation.mdx, v2/nodejs_versioned_docs/version-6.1.X/installation.mdx, v2/nodejs_versioned_docs/version-7.0.X/installation.mdx, v2/nodejs_versioned_docs/version-7.1.X/installation.mdx, v2/nodejs_versioned_docs/version-7.2.X/installation.mdx, v2/website/installation.mdx, v2/website_versioned_docs/version-8.1.X/installation.mdx, v2/website_versioned_docs/version-8.2.X/installation.mdx
=> Fix typos in docs

pro/docs/about-payments.md
=> Missing Puctuation

v2/session/quick-setup/backend.mdx
Minot typo fixed in notification content
=> fixes minor typo

v2/contribute/checklists/saas/mysql-rds.md
mysql rds checklist (minimum set of queries that need to be executed when adding new mysql rds instance)
=> mysql rds checklist

v2/emailpassword/quick-setup/backend.mdx, v2/passwordless/quick-setup/backend.mdx, v2/session/quick-setup/backend.mdx, v2/src/plugins/codeTypeChecking/pythonEnv/requirements.txt, v2/thirdparty/quick-setup/backend.mdx, v2/thirdpartyemailpassword/quick-setup/backend.mdx
Code snippet changes for new python Sdk version
=> fixes python code snippets (python v0.6)

v2/emailpassword/common-customizations/password-hashing/about.mdx, v2/emailpassword/common-customizations/password-hashing/argon2.mdx, v2/emailpassword/common-customizations/password-hashing/bcrypt.mdx, v2/emailpassword/sidebars.js, v2/thirdpartyemailpassword/common-customizations/password-hashing/about.mdx, v2/thirdpartyemailpassword/common-customizations/password-hashing/argon2.mdx, v2/thirdpartyemailpassword/common-customizations/password-hashing/bcrypt.mdx, v2/thirdpartyemailpassword/sidebars.js
Adds docs for password hashing
-https://github.com/supertokens/supertokens-core/issues/410
=> Argon2 docs

v2/emailpassword/nextjs/protecting-route.mdx, v2/passwordless/nextjs/protecting-route.mdx, v2/thirdparty/nextjs/protecting-route.mdx, v2/thirdpartyemailpassword/nextjs/protecting-route.mdx, v2/thirdpartypasswordless/nextjs/protecting-route.mdx
Type checking ran into problems with react 18 types.
-
=> fix types for react 18

v2/emailpassword/sidebars.js, v2/emailpassword/troubleshooting/how-to-troubleshoot.mdx, v2/passwordless/sidebars.js, v2/passwordless/troubleshooting/how-to-troubleshoot.mdx, v2/session/sidebars.js, v2/session/troubleshooting/how-to-troubleshoot.mdx, v2/src/components/tabs/OSTabs.tsx, v2/thirdparty/sidebars.js, v2/thirdparty/troubleshooting/how-to-troubleshoot.mdx, v2/thirdpartyemailpassword/sidebars.js, v2/thirdpartyemailpassword/troubleshooting/how-to-troubleshoot.mdx, v2/thirdpartypasswordless/sidebars.js, v2/thirdpartypasswordless/troubleshooting/how-to-troubleshoot.mdx
Adds page for debug logs for backend SDK
- https://github.com/supertokens/supertokens-core/issues/411
=> Debug logs for backend SDK

v2/session/reusableMD/networkInterceptors.mdx
Fix spelling issue in documentation, not urgent.
none
none
=> Fix spelling issue

v2/thirdparty/common-customizations/saml/what-is-saml.mdx, v2/thirdparty/common-customizations/saml/with-boxyhq/integration-steps.mdx, v2/thirdparty/common-customizations/saml/with-boxyhq/what-is-boxyhq.mdx, v2/thirdpartyemailpassword/common-customizations/saml/what-is-saml.mdx, v2/thirdpartyemailpassword/common-customizations/saml/with-boxyhq/integration-steps.mdx, v2/thirdpartyemailpassword/common-customizations/saml/with-boxyhq/what-is-boxyhq.mdx, v2/thirdpartypasswordless/common-customizations/saml/what-is-saml.mdx, v2/thirdpartypasswordless/common-customizations/saml/with-boxyhq/integration-steps.mdx, v2/thirdpartypasswordless/common-customizations/saml/with-boxyhq/what-is-boxyhq.mdx
A few tweaks to the SAML & BoxyHQ docs.
n/a
=> Minor tweaks to the docs for SAML, BoxyHQ

v2/contribute/checklists/saas/scaling-prod-instances.md
- instructions to add load-balancer for saas apps
=> updated instruction to add access logs when adding load balancer

v2/contribute/checklists/saas/scaling-prod-instances.md
- more steps while adding s3 bucket for load balancer
=> block public access for the s3 bucket created for load balancer

v2/contribute/checklists/saas/add-new-region.md, v2/contribute/checklists/saas/issues-removing-app.md, v2/contribute/checklists/saas/mysql-rds.md, v2/contribute/sidebars.js
- adding steps for complaince while adding new RDS cluster
- how to remove pending postgresql connections when trying to remove a saas app
=> complaince changes when adding new RDS cluster

v2/contribute/checklists/saas/add-new-region.md
complaince changes when adding a new region
=> complaince changes when adding a new region

v2/emailpassword/common-customizations/email-verification/about.mdx, v2/emailpassword/common-customizations/email-verification/email-verification-email.mdx, v2/emailpassword/common-customizations/reset-password/about.mdx, v2/emailpassword/common-customizations/reset-password/password-reset-email.mdx, v2/thirdparty/common-customizations/email-verification/about.mdx, v2/thirdparty/common-customizations/email-verification/email-verification-email.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/about.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/email-verification-email.mdx, v2/thirdpartyemailpassword/common-customizations/reset-password/about.mdx, v2/thirdpartyemailpassword/common-customizations/reset-password/password-reset-email.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/about.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/email-verification-email.mdx
Email verification form UI images:
- https://test.supertokens.com/docs/emailpassword/common-customizations/email-verification/about
- https://test.supertokens.com/docs/thirdparty/common-customizations/email-verification/about
- https://test.supertokens.com/docs/thirdpartyemailpassword/common-customizations/email-verification/about
- https://test.supertokens.com/docs/thirdpartypasswordless/common-customizations/email-verification/about
Email verification email:
- https://test.supertokens.com/docs/emailpassword/common-customizations/email-verification/email-verification-email
- https://test.supertokens.com/docs/thirdparty/common-customizations/email-verification/email-verification-email
- https://test.supertokens.com/docs/thirdpartyemailpassword/common-customizations/email-verification/email …
=> Added alt text to email verification, reset password images and removed extra title from reset password page

v2/emailpassword/testing/testing-with-postman.mdx, v2/passwordless/testing/testing-with-postman.mdx, v2/session/testing/testing-with-postman.mdx, v2/thirdparty/testing/testing-with-postman.mdx, v2/thirdpartyemailpassword/testing/testing-with-postman.mdx, v2/thirdpartypasswordless/testing/testing-with-postman.mdx
Testing with postman images
- https://test.supertokens.com/docs/emailpassword/testing/testing-with-postman
- https://test.supertokens.com/docs/passwordless/testing/testing-with-postman
- https://test.supertokens.com/docs/session/testing/testing-with-postman
- https://test.supertokens.com/docs/thirdparty/testing/testing-with-postman
- https://test.supertokens.com/docs/thirdpartyemailpassword/testing/testing-with-postman
- https://test.supertokens.com/docs/thirdpartypasswordless/testing/testing-with-postman
- #305 
No TODOs remaining
=> Added alt text to postman testing images

v2/emailpassword/advanced-customizations/react-component-override/usage.mdx, v2/emailpassword/common-customizations/password-managers.mdx, v2/emailpassword/common-customizations/styling/changing-colours.mdx, v2/passwordless/advanced-customizations/react-component-override/usage.mdx, v2/passwordless/common-customizations/styling/changing-colours.mdx, v2/thirdparty/advanced-customizations/react-component-override/usage.mdx, v2/thirdparty/common-customizations/styling/changing-colours.mdx, v2/thirdpartyemailpassword/advanced-customizations/react-component-override/usage.mdx, v2/thirdpartyemailpassword/common-customizations/password-managers.mdx, v2/thirdpartyemailpassword/common-customizations/styling/changing-colours.mdx, v2/thirdpartypasswordless/advanced-customizations/react-component-override/usage.mdx, v2/thirdpartypasswordless/common-customizations/styling/changing-colours.mdx
React component override docs
- https://test.supertokens.com/docs/emailpassword/advanced-customizations/react-component-override/usage
- https://test.supertokens.com/docs/passwordless/advanced-customizations/react-component-override/usage
- https://test.supertokens.com/docs/thirdparty/advanced-customizations/react-component-override/usage
- https://test.supertokens.com/docs/thirdpartyemailpassword/advanced-customizations/react-component-override/usage
- https://test.supertokens.com/docs/thirdpartypasswordless/advanced-customizations/react-component-override/usage
Password managers
- https://test.supertokens.com/docs/emailpassword/common-customizations/password-managers
- https://test.supertokens.com/docs/thirdpartyemailpassword/common-customizations/password-managers
Changing colors
- …
=> Added alt text to images in common customizations docs

v2/emailpassword/common-customizations/sessions/about.mdx, v2/emailpassword/migration/from-auth0/session-migration.mdx, v2/passwordless/common-customizations/sessions/about.mdx, v2/passwordless/migration/from-auth0/session-migration.mdx, v2/session/introduction.mdx, v2/session/migration/from-auth0/session-migration.mdx, v2/thirdparty/common-customizations/sessions/about.mdx, v2/thirdparty/migration/from-auth0/session-migration.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/about.mdx, v2/thirdpartyemailpassword/migration/from-auth0/session-migration.mdx, v2/thirdpartypasswordless/common-customizations/sessions/about.mdx, v2/thirdpartypasswordless/migration/from-auth0/session-migration.mdx
Added alt text to session session flow images
- https://test.supertokens.com/docs/emailpassword/common-customizations/sessions/about
- https://test.supertokens.com/docs/passwordless/common-customizations/sessions/about
- https://test.supertokens.com/docs/session/introduction
- https://test.supertokens.com/docs/thirdparty/common-customizations/sessions/about
- https://test.supertokens.com/docs/thirdpartyemailpassword/common-customizations/sessions/about
- https://test.supertokens.com/docs/thirdpartypasswordless/common-customizations/sessions/about
Added alt text to session migration images
- https://test.supertokens.com/docs/emailpassword/migration/from-auth0/session-migration
- https://test.supertokens.com/docs/passwordless/migration/from-auth0/session-migration
- …
=> Add alt text to session flow diagrams and session migration flowcharts

v2/change_me/introduction.mdx, v2/src/css/custom.css
- #292 
- Update colors for the blockquote element
- Make the spacing on top and bottom consistent
=> Update styles for blockquotes and make the padding top and bottom consistent for it

v2/community/database-setup/mysql.mdx, v2/community/database-setup/postgresql.mdx, v2/emailpassword/quick-setup/database-setup/mysql.mdx, v2/emailpassword/quick-setup/database-setup/postgresql.mdx, v2/passwordless/quick-setup/database-setup/mysql.mdx, v2/passwordless/quick-setup/database-setup/postgresql.mdx, v2/session/quick-setup/database-setup/mysql.mdx, v2/session/quick-setup/database-setup/postgresql.mdx, v2/thirdparty/quick-setup/database-setup/mysql.mdx, v2/thirdparty/quick-setup/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/quick-setup/database-setup/mysql.mdx, v2/thirdpartyemailpassword/quick-setup/database-setup/postgresql.mdx, v2/thirdpartypasswordless/quick-setup/database-setup/mysql.mdx, v2/thirdpartypasswordless/quick-setup/database-setup/postgresql.mdx
Adds db queries to create tables and indexes related to the user roles feature
- https://github.com/supertokens/supertokens-core/issues/382
- none
=> chore: adds create table docs for user-roles

v2/session/advanced-customizations/frontend-hooks/handle-event.mdx, v2/src/plugins/codeTypeChecking/jsEnv/package.json
Added ACCESS_TOKEN_UPDATED_EVENT to session event handlers page
-   supertokens/supertokens-auth-react#397 
-   supertokens/supertokens-auth-react#446
-   supertokens/supertokens-website#121 
-
=> Added ACCESS_TOKEN_UPDATED_EVENT to session event handlers

v2/emailpassword/migration/from-auth0/session-migration.mdx, v2/passwordless/migration/from-auth0/session-migration.mdx, v2/session/migration/from-auth0/session-migration.mdx, v2/thirdparty/migration/from-auth0/session-migration.mdx, v2/thirdpartyemailpassword/migration/from-auth0/about.mdx, v2/thirdpartyemailpassword/migration/from-auth0/session-migration.mdx, v2/thirdpartypasswordless/migration/from-auth0/session-migration.mdx
Grammar fixs 
- none
- ~~[ ] Algolia search needs to be updated? (If there is a new sub docs project, then yes)~~
- ~~[ ] Sitemap needs to be updated? (If there is a new sub docs project, then yes)~~
- ~~[ ] Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)~~
- ~~[ ] Changes required to the demo apps corresponding to the docs?~~
- none
=> docs: fixs

v2/community/sdks.mdx, v2/emailpassword/sdks.mdx, v2/passwordless/sdks.mdx, v2/session/sdks.mdx, v2/thirdparty/sdks.mdx, v2/thirdpartyemailpassword/sdks.mdx, v2/thirdpartypasswordless/sdks.mdx
=> chore: Update vanilla JS SDK link to point to web-js

v2/src/plugins/codeTypeChecking/jsEnv/package.json
- Updates the dependency for typescript code checking to use the latest version of supertokens-website (`12.0.0`)
- ...
=> chore: Update jsEnv to use latest supertokens-website

v2/emailpassword/common-customizations/email-verification/embed-in-page.mdx, v2/emailpassword/common-customizations/embed-sign-in-up-form.mdx, v2/emailpassword/common-customizations/reset-password/embed-in-page.mdx, v2/passwordless/common-customizations/change-magic-link-url.mdx, v2/passwordless/common-customizations/embed-sign-in-up-form.mdx, v2/src/plugins/codeTypeChecking/jsEnv/package.json, v2/thirdparty/common-customizations/email-verification/embed-in-page.mdx, v2/thirdparty/common-customizations/embed-sign-in-up-form.mdx, v2/thirdpartyemailpassword/advanced-customizations/frontend-functions-override/usage.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/embed-in-page.mdx, v2/thirdpartyemailpassword/common-customizations/embed-sign-in-up-form.mdx, v2/thirdpartyemailpassword/common-customizations/reset-password/embed-in-page.mdx, v2/thirdpartypasswordless/advanced-customizations/frontend-functions-override/usage.mdx, v2/thirdpartypasswordless/common-customizations/change-magic-link-url.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/embed-in-page.mdx, v2/thirdpartypasswordless/common-customizations/embed-sign-in-up-form.mdx
=> chore: Update jsEnv to use latest auth react version

v2/passwordless/advanced-customizations/apis-override/custom-response/api-override.mdx, v2/passwordless/advanced-customizations/apis-override/custom-response/throwing-error.mdx, v2/passwordless/sidebars.js, v2/src/plugins/markdownVariables.json
Adds missing section about custom responses in API override section of passwordless recipe
- none
- ~~[ ] Algolia search needs to be updated? (If there is a new sub docs project, then yes)~~ 
- ~~[ ] Sitemap needs to be updated? (If there is a new sub docs project, then yes)~~
- ~~[ ] Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)~~
- ~~[ ] Changes required to the demo apps corresponding to the docs?~~
- none
=> Adds custom responses section in api overrides for passwordless recipe

CONTRIBUTING.md, v2/src/components/tabs/FrontendSDKTabs.tsx, v2/src/components/utils.ts, v2/thirdpartyemailpassword/quick-setup/frontend.mdx
Adds COPY-TABS functionality
- none
-
=> Adds refrence tabs feature

v2/emailpassword/email-delivery/smtp/change-email-content.mdx, v2/emailpassword/email-delivery/smtp/configure-smtp.mdx, v2/passwordless/email-delivery/smtp/change-email-content.mdx, v2/passwordless/email-delivery/smtp/configure-smtp.mdx, v2/passwordless/sms-delivery/supertokens-sms-service.mdx, v2/passwordless/sms-delivery/twilio/change-sms-content.mdx, v2/passwordless/sms-delivery/twilio/configure-twilio.mdx, v2/src/plugins/codeTypeChecking/goEnv/go.mod, v2/src/plugins/codeTypeChecking/goEnv/go.sum, v2/src/plugins/codeTypeChecking/jsEnv/package.json, v2/thirdparty/advanced-customizations/apis-override/usage.mdx, v2/thirdparty/email-delivery/smtp/change-email-content.mdx, v2/thirdparty/email-delivery/smtp/configure-smtp.mdx, v2/thirdpartyemailpassword/email-delivery/smtp/change-email-content.mdx, v2/thirdpartyemailpassword/email-delivery/smtp/configure-smtp.mdx, v2/thirdpartypasswordless/email-delivery/smtp/change-email-content.mdx, v2/thirdpartypasswordless/email-delivery/smtp/configure-smtp.mdx, v2/thirdpartypasswordless/sms-delivery/supertokens-sms-service.mdx, v2/thirdpartypasswordless/sms-delivery/twilio/change-sms-content.mdx, v2/thirdpartypasswordless/sms-delivery/twilio/configure-twilio.mdx
Update code snippets for new interface
=> Email sms code fixes

v2/src/components/question/index.tsx
Adds persistent question feature 
- none
- none
=> feat: adds persistent question feature

v2/emailpassword/migration/from-auth0/about.mdx, v2/passwordless/migration/from-auth0/about.mdx, v2/thirdparty/migration/from-auth0/about.mdx, v2/thirdpartyemailpassword/migration/from-auth0/about.mdx, v2/thirdpartypasswordless/migration/from-auth0/about.mdx
Some typo fixes in migration docs
- none
- none
=> Migration guide typo fixes

v2/emailpassword/quick-setup/frontend.mdx, v2/thirdpartyemailpassword/quick-setup/frontend.mdx
Adds angular code tabs to Email Password Recipe
- https://github.com/supertokens/docs/pull/349
- none
=> Adds angular tabs to ep

v2/passwordless/common-customizations/get-user-info.mdx, v2/passwordless/quick-setup/frontend.mdx, v2/session/common-customizations/sessions/checking-session-front-end.mdx, v2/session/common-customizations/sessions/handling-session-expiry.mdx, v2/session/common-customizations/sessions/securing-component.mdx, v2/session/common-customizations/sessions/user-information-front-end.mdx, v2/session/quick-setup/frontend.mdx, v2/thirdparty/quick-setup/frontend.mdx, v2/thirdpartyemailpassword/quick-setup/frontend.mdx, v2/thirdpartypasswordless/common-customizations/get-user-info.mdx, v2/thirdpartypasswordless/quick-setup/frontend.mdx
Adds tabs for EmailPassword, ThirdParty, ThirdPartyPasswordless, Passwordless, Session recipies
- none
=> Adds remaining angular tabs

v2/emailpassword/quick-setup/frontend.mdx, v2/emailpassword/serverless/with-netlify/frontend.mdx, v2/emailpassword/troubleshooting/how-to-troubleshoot.mdx, v2/passwordless/quick-setup/frontend.mdx, v2/passwordless/serverless/with-netlify/frontend.mdx, v2/passwordless/troubleshooting/how-to-troubleshoot.mdx, v2/session/quick-setup/frontend.mdx, v2/session/serverless/with-netlify/frontend.mdx, v2/session/troubleshooting/how-to-troubleshoot.mdx, v2/thirdparty/quick-setup/frontend.mdx, v2/thirdparty/serverless/with-netlify/frontend.mdx, v2/thirdparty/troubleshooting/how-to-troubleshoot.mdx, v2/thirdpartyemailpassword/quick-setup/frontend.mdx, v2/thirdpartyemailpassword/serverless/with-netlify/frontend.mdx, v2/thirdpartyemailpassword/troubleshooting/how-to-troubleshoot.mdx, v2/thirdpartypasswordless/quick-setup/frontend.mdx, v2/thirdpartypasswordless/serverless/with-netlify/frontend.mdx, v2/thirdpartypasswordless/troubleshooting/how-to-troubleshoot.mdx
Changes made for:
- Quick setup
- Troubleshooting guides
- Serverless
-
=> chore: Update imports for supertokens-website for quick setup, serverless and troubleshooting

v2/emailpassword/migration/from-auth0/session-migration.mdx, v2/passwordless/migration/from-auth0/session-migration.mdx, v2/phonepassword/frontend.mdx, v2/session/advanced-customizations/frontend-functions-override/usage.mdx, v2/session/advanced-customizations/frontend-hooks/handle-event.mdx, v2/session/advanced-customizations/frontend-hooks/pre-api.mdx, v2/session/migration/from-auth0/session-migration.mdx, v2/session/reusableMD/networkInterceptors.mdx, v2/session/using-with-faunadb.mdx, v2/thirdparty/migration/from-auth0/session-migration.mdx, v2/thirdpartyemailpassword/migration/from-auth0/session-migration.mdx, v2/thirdpartypasswordless/migration/from-auth0/session-migration.mdx
=> chore: Update imports for supertokens-website for remaining files

v2/emailpassword/common-customizations/sessions/update-jwt-payload.mdx, v2/emailpassword/common-customizations/sessions/update-session-data.mdx, v2/emailpassword/common-customizations/sessions/with-jwt/update-jwt.mdx, v2/passwordless/common-customizations/sessions/update-jwt-payload.mdx, v2/passwordless/common-customizations/sessions/update-session-data.mdx, v2/passwordless/common-customizations/sessions/with-jwt/update-jwt.mdx, v2/session/common-customizations/sessions/update-jwt-payload.mdx, v2/session/common-customizations/sessions/update-session-data.mdx, v2/session/common-customizations/sessions/with-jwt/update-jwt.mdx, v2/src/plugins/codeTypeChecking/goEnv/go.mod, v2/src/plugins/codeTypeChecking/goEnv/go.sum, v2/thirdparty/common-customizations/sessions/update-jwt-payload.mdx, v2/thirdparty/common-customizations/sessions/update-session-data.mdx, v2/thirdparty/common-customizations/sessions/with-jwt/update-jwt.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/update-jwt-payload.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/update-session-data.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/with-jwt/update-jwt.mdx, v2/thirdpartypasswordless/common-customizations/sessions/update-jwt-payload.mdx, v2/thirdpartypasswordless/common-customizations/sessions/update-session-data.mdx, v2/thirdpartypasswordless/common-customizations/sessions/with-jwt/update-jwt.mdx
Fixed snippets for golang breaking changes
=> fix: fixed snippets for golang

v2/session/user-roles/managing-roles-and-sessions.mdx
=> Userroles golang snippets

v2/emailpassword/user-roles/managing-roles-and-users.mdx, v2/passwordless/user-roles/managing-roles-and-users.mdx, v2/session/user-roles/managing-roles-and-users.mdx, v2/thirdparty/user-roles/managing-roles-and-users.mdx, v2/thirdpartyemailpassword/user-roles/managing-roles-and-users.mdx, v2/thirdpartypasswordless/user-roles/managing-roles-and-users.mdx, v2/userroles/managing-roles-and-users.mdx
=> UserRoles doc fix

v2/emailpassword/quick-setup/frontend.mdx, v2/passwordless/quick-setup/frontend.mdx, v2/session/quick-setup/frontend.mdx, v2/thirdparty/quick-setup/frontend.mdx, v2/thirdpartyemailpassword/quick-setup/frontend.mdx, v2/thirdpartypasswordless/quick-setup/frontend.mdx
=> Update quick setup guide for supertokens-web-js with html scripts

v2/mfa/backend/first-factor.mdx, v2/mfa/backend/protecting-api.mdx, v2/mfa/backend/second-factor.mdx
Add python snippets for Multi Factor Authentication
=> feat: Add python snippets for Multi Factor Authentication

v2/mfa/backend/first-factor.mdx, v2/mfa/backend/protecting-api.mdx, v2/mfa/backend/second-factor.mdx
=> fix: 2-fa golang snippets

v2/emailpassword/sidebars.js, v2/package.json, v2/passwordless/sidebars.js, v2/session/sidebars.js, v2/src/theme/DocSidebar/index.js, v2/thirdparty/sidebars.js, v2/thirdpartyemailpassword/sidebars.js, v2/thirdpartypasswordless/sidebars.js
1. Renamed "Quick Setup" to "Initialization"
2. Rename "Common Customizations" to "Additional features and customizations"
3. Group all third party integrations under a single section in the sidebar called "Integrations"
4. Group AppInfo, API + SDK references and compatibility table in a single section in the sidebar called "References and compatibility"
=> refactor: Docs restructure sidebar

v2/contribute/checklists/saas/db-restore.md, v2/contribute/sidebars.js
- added checklist for db restoration process using automated backups
=> added db restore checklist

v2/contribute/checklists/saas/adding-instances-to-load-blancer.md, v2/contribute/sidebars.js
- checklist doc regarding how to add instance to an existing load balancer
=> checklist doc regarding how to add instance to an existing load balancer

v2/src/theme/NavbarItem/SignUpButton/style.css
- Uses a pointer when hovering the sign up button (previously would default to text index cursor or a plan arrow pointer)
=> bugfix: Fix cursor for sign up button in the navbar

v2/thirdpartyemailpassword/common-customizations/sessions/with-jwt/about.mdx
=> fix spelling error in jwt session page

v2/contribute/checklists/saas/scaling-prod-instances.md
- adding step while adding load balancer for a production deployment of an app
=> adding step while adding load balancer for an app

v2/thirdpartypasswordless/migration/from-auth0/about.mdx, v2/thirdpartypasswordless/sidebars.js
Uncomments TPPasswordless migration guide from sidebar
=> adds thirdPartyPasswordless migration guide docs

v2/emailpassword/quick-setup/frontend.mdx, v2/passwordless/quick-setup/frontend.mdx, v2/src/plugins/codeTypeChecking/jsEnv/package.json, v2/thirdparty/quick-setup/frontend.mdx, v2/thirdpartyemailpassword/quick-setup/frontend.mdx, v2/thirdpartypasswordless/quick-setup/frontend.mdx
=> Removes vue related dependencies

CONTRIBUTING.md, v2/change_me/ui-switcher.mdx, v2/docusaurus.config.js, v2/src/components/preBuiltOrCustomUISwitcher/index.tsx, v2/src/components/tabs/FrontendSDKTabs.tsx, v2/src/css/custom.css, v2/src/plugins/tocHeaderProcessor/index.js, v2/src/plugins/tocHeaderProcessor/postHeaderFixer.js, v2/src/theme/DocItem/index.js, v2/src/theme/TOC/index.js, v2/src/theme/TOC/styles.module.css
Adds component for pre built vs custom UI switcher
=> Custom pre built switcher

v2/docusaurus.config.js, v2/src/components/appInfoForm/formItem.tsx, v2/src/components/appInfoForm/style.css
Update the AppInfoForm coloring and font
- https://github.com/supertokens/main-website/issues/897
NA
=> fix: New form color

v2/emailpassword/common-customizations/email-verification/handling-email-verification-success.mdx, v2/emailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/emailpassword/user-roles/protecting-routes.mdx, v2/mfa/backend/first-factor.mdx, v2/mfa/backend/protecting-api.mdx, v2/mfa/backend/second-factor.mdx, v2/passwordless/common-customizations/email-verification/handling-email-verification-success.mdx, v2/passwordless/common-customizations/email-verification/protecting-routes.mdx, v2/passwordless/user-roles/protecting-routes.mdx, v2/thirdparty/common-customizations/email-verification/handling-email-verification-success.mdx, v2/thirdparty/common-customizations/email-verification/protecting-routes.mdx, v2/thirdparty/user-roles/protecting-routes.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/handling-email-verification-success.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartyemailpassword/user-roles/protecting-routes.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/handling-email-verification-success.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartypasswordless/user-roles/protecting-routes.mdx, v2/userroles/protecting-routes.mdx
=> fix: golang snippets

v2/src/components/appInfoForm/index.tsx
- Fixes compilation errors in app info
- Refactors placeholder value and popup text for website domain in app info
...
=> refactor: Refactor to placeholder string and hint text for website domain

CONTRIBUTING.md
Add step to setup hooks after `npm i`
NA
NA
=> add hooks in contributing

v2/thirdpartyemailpassword/quick-setup/core/self-hosted-with-docker.mdx
See https://discord.com/channels/603466164219281420/644849840475602944/1019549150595006504
=> `hello` route liveness and readiness probe

v2/community/database-setup/mysql.mdx, v2/community/database-setup/postgresql.mdx, v2/emailpassword/quick-setup/database-setup/mysql.mdx, v2/emailpassword/quick-setup/database-setup/postgresql.mdx, v2/passwordless/quick-setup/database-setup/mysql.mdx, v2/passwordless/quick-setup/database-setup/postgresql.mdx, v2/session/quick-setup/database-setup/mysql.mdx, v2/session/quick-setup/database-setup/postgresql.mdx, v2/thirdparty/quick-setup/database-setup/mysql.mdx, v2/thirdparty/quick-setup/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/quick-setup/database-setup/mysql.mdx, v2/thirdpartyemailpassword/quick-setup/database-setup/postgresql.mdx, v2/thirdpartypasswordless/quick-setup/database-setup/mysql.mdx, v2/thirdpartypasswordless/quick-setup/database-setup/postgresql.mdx
=> updates table creation queries

v2/emailpassword/email-delivery/smtp/configure-smtp.mdx, v2/passwordless/email-delivery/smtp/configure-smtp.mdx, v2/src/plugins/codeTypeChecking/pythonEnv/requirements.txt, v2/thirdparty/email-delivery/smtp/configure-smtp.mdx, v2/thirdpartyemailpassword/email-delivery/smtp/configure-smtp.mdx, v2/thirdpartypasswordless/email-delivery/smtp/configure-smtp.mdx
Show usage of new username field in SMTPSettings for the python SDK.
- https://github.com/supertokens/supertokens-python/issues/217
=> feat(python): Show usage of new username field in SMTPSettings

v2/emailpassword/migration/about.mdx, v2/emailpassword/migration/data-migration.mdx, v2/emailpassword/migration/session-migration.mdx, v2/emailpassword/sidebars.js, v2/passwordless/migration/about.mdx, v2/passwordless/migration/data-migration.mdx, v2/passwordless/migration/session-migration.mdx, v2/passwordless/sidebars.js, v2/thirdparty/migration/about.mdx, v2/thirdparty/migration/data-migration.mdx, v2/thirdparty/migration/session-migration.mdx, v2/thirdparty/sidebars.js, v2/thirdpartyemailpassword/migration/about.mdx, v2/thirdpartyemailpassword/migration/data-migration.mdx, v2/thirdpartyemailpassword/migration/session-migration.mdx, v2/thirdpartyemailpassword/sidebars.js, v2/thirdpartypasswordless/migration/about.mdx, v2/thirdpartypasswordless/migration/data-migration.mdx, v2/thirdpartypasswordless/migration/session-migration.mdx, v2/thirdpartypasswordless/sidebars.js
=> Adds remaining migration docs

v2/emailpassword/custom-ui/handling-session-tokens.mdx, v2/emailpassword/custom-ui/init/frontend.mdx, v2/passwordless/custom-ui/handling-session-tokens.mdx, v2/passwordless/custom-ui/init/frontend.mdx, v2/src/plugins/codeTypeChecking/kotlinEnv/app/build.gradle, v2/thirdparty/custom-ui/handling-session-tokens.mdx, v2/thirdparty/custom-ui/init/frontend.mdx, v2/thirdpartyemailpassword/custom-ui/handling-session-tokens.mdx, v2/thirdpartyemailpassword/custom-ui/init/frontend.mdx, v2/thirdpartypasswordless/custom-ui/handling-session-tokens.mdx, v2/thirdpartypasswordless/custom-ui/init/frontend.mdx
Adds pre connect callback to snippets to help explain how users can add headers, set request method etc when using HttpURLConnection on Android
-
=> Add pre connect callback to HttpURLConnection snippets

v2/src/plugins/copyDocsAndCodeTypeChecking.js
=> Fix ios code type checking

v2/emailpassword/custom-ui/email-password-login.mdx, v2/thirdpartyemailpassword/custom-ui/email-password-login.mdx
Small typo, follwing -> following
=> Spelling Error

v2/emailpassword/advanced-customizations/apis-override/custom-response/throwing-error.mdx, v2/emailpassword/nextjs/setting-up-backend.mdx, v2/passwordless/advanced-customizations/apis-override/custom-response/throwing-error.mdx, v2/passwordless/nextjs/setting-up-backend.mdx, v2/session/advanced-customizations/apis-override/custom-response/throwing-error.mdx, v2/thirdparty/advanced-customizations/apis-override/custom-response/throwing-error.mdx, v2/thirdparty/nextjs/setting-up-backend.mdx, v2/thirdpartyemailpassword/advanced-customizations/apis-override/custom-response/throwing-error.mdx, v2/thirdpartyemailpassword/nextjs/setting-up-backend.mdx, v2/thirdpartypasswordless/advanced-customizations/apis-override/custom-response/throwing-error.mdx, v2/thirdpartypasswordless/nextjs/setting-up-backend.mdx
- Modifies NextJS snippets that use middleware to avoid having caching issues
- https://github.com/supertokens/supertokens-node/issues/409
=> Add cache control headers to snippets using the middleware with NextJS

v2/emailpassword/pre-built-ui/setup/frontend.mdx, v2/passwordless/pre-built-ui/setup/frontend.mdx, v2/thirdparty/pre-built-ui/setup/frontend.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/frontend.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/frontend.mdx
=> fix: vue prebuilt docs fixs

v2/contribute/checklists/saas/launch-boxyhq-containers.md
=> bug fix busyhq step

v2/emailpassword/pre-built-ui/setup/frontend.mdx, v2/passwordless/pre-built-ui/setup/frontend.mdx, v2/thirdparty/pre-built-ui/setup/frontend.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/frontend.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/frontend.mdx
Make introduction of pre built UI docs for angular and vue clear
=> Vue angular docs updates

v2/contribute/checklists/saas/adding-cores-for-user.md, v2/contribute/sidebars.js
- Steps on how to add cores for user
=> adding new core for user

v2/src/theme/DocSidebar/index.js, v2/src/theme/DocSidebar/styles.module.css, v2/thirdpartyemailpassword/sidebars.js
=> chore: Refactor sidebar highlight based on design review

v2/emailpassword/sidebars.js, v2/passwordless/sidebars.js, v2/session/sidebars.js, v2/src/theme/DocSidebar/index.js, v2/thirdparty/sidebars.js, v2/thirdpartyemailpassword/sidebars.js, v2/thirdpartypasswordless/sidebars.js
=> refactor: Remove integrations from the start here section and add introduction to it

v2/contribute/decisions/0000-use-markdown-any-decision-records.mdx, v2/contribute/decisions/00XX-template.mdx, v2/contribute/decisions/about.mdx, v2/contribute/decisions/passwordless/0001-allow-opening-login-urls-on-new-devices.mdx, v2/contribute/decisions/passwordless/0002-show-user-info-on-passwordless-link-sign-inup-screen.mdx, v2/contribute/decisions/session/0001-support-for-header-based-auth.mdx, v2/contribute/decisions/session/0002-auth-method-chosen-by-frontend-preference-and-backend-validation.mdx, v2/contribute/decisions/session/0003-default-to-cookie-based-if-rid-header-otherwise.mdx, v2/contribute/decisions/session/0004-attaching-auth-mode-preference.mdx, v2/contribute/decisions/session/0006-token-header-names-follow-cookie-names.mdx, v2/contribute/decisions/session/0007-session-verification-should-allow-fallback.mdx, v2/contribute/decisions/session/0007-session-verification-should-reject-request-with-wrong-auth-method.mdx, v2/contribute/decisions/session/0008-change-auth-method-only-in-refresh.mdx, v2/contribute/decisions/session/0009-disable-anti-csrf-in-header-based-auth.mdx, v2/contribute/decisions/session/0010-clear-cookies-if-present-when-clearing-session-in-header-mode.mdx, v2/contribute/decisions/session/0011-remove-id-refresh-token.mdx, v2/contribute/decisions/session/0012-keep-front-token-in-header-mode.mdx, v2/contribute/decisions/session/0013-return-unauthorised-for-non-supertokens-issued-access-tokens.mdx, v2/contribute/decisions/session/0014-keep-adding-withCredentials-in-header-mode.mdx, v2/contribute/decisions/session/0015-jwt-compatibility.mdx, v2/contribute/decisions/session/0016-store-tokens-in-cookies-in-header-mode.mdx, v2/contribute/sidebars.js, v2/src/components/decisionLogs/ArgumentCon.tsx, v2/src/components/decisionLogs/ArgumentNeut.tsx, v2/src/components/decisionLogs/ArgumentPro.tsx, v2/src/components/decisionLogs/DecisionHeader.tsx, v2/src/components/decisionLogs/DecisionStatusAdmonition.tsx, v2/src/components/decisionLogs/decisionLogs.css
=> Adds decision logs to the contribution docs

v2/emailpassword/serverless/with-netlify/auth-serverless.mdx, v2/passwordless/serverless/with-netlify/auth-serverless.mdx, v2/session/serverless/with-netlify/auth-serverless.mdx, v2/thirdparty/serverless/with-netlify/auth-serverless.mdx, v2/thirdpartyemailpassword/serverless/with-netlify/auth-serverless.mdx, v2/thirdpartypasswordless/serverless/with-netlify/auth-serverless.mdx
=> auth middleware apis cors update

static/scripts/commonDocsBuilder.js, v2/src/plugins/reactBundle.js, v2/src/theme/DocSidebar/index.js
=> refactor: Replace driftt with intercom

v2/emailpassword/custom-ui/init/dashboard.mdx, v2/emailpassword/pre-built-ui/setup/dashboard.mdx, v2/passwordless/custom-ui/init/dashboard.mdx, v2/passwordless/pre-built-ui/setup/dashboard.mdx, v2/thirdparty/custom-ui/init/dashboard.mdx, v2/thirdparty/pre-built-ui/setup/dashboard.mdx, v2/thirdpartyemailpassword/custom-ui/init/dashboard.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/dashboard.mdx, v2/thirdpartypasswordless/custom-ui/init/dashboard.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/dashboard.mdx
=> fix: Fix language for code snippet for CSP

.circleci/config.yml, v2/package.json
=> chore: Add CICD code type checking for ios

v2/emailpassword/common-customizations/changing-base-path/api-base-path.mdx, v2/emailpassword/common-customizations/sessions/multiple-api-endpoints.mdx, v2/passwordless/common-customizations/changing-base-path/api-base-path.mdx, v2/passwordless/common-customizations/sessions/multiple-api-endpoints.mdx, v2/session/common-customizations/changing-base-path/api-base-path.mdx, v2/session/common-customizations/sessions/multiple-api-endpoints.mdx, v2/src/plugins/codeTypeChecking/iosenv/Pods/Pods.xcodeproj/project.pbxproj, v2/src/plugins/codeTypeChecking/iosenv/Pods/Pods.xcodeproj/xcuserdata/nemi.xcuserdatad/xcschemes/xcschememanagement.plist, v2/src/plugins/codeTypeChecking/iosenv/iosenv.xcodeproj/project.pbxproj, v2/thirdparty/common-customizations/changing-base-path/api-base-path.mdx, v2/thirdparty/common-customizations/sessions/multiple-api-endpoints.mdx, v2/thirdpartyemailpassword/common-customizations/changing-base-path/api-base-path.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/multiple-api-endpoints.mdx, v2/thirdpartypasswordless/common-customizations/changing-base-path/api-base-path.mdx, v2/thirdpartypasswordless/common-customizations/sessions/multiple-api-endpoints.mdx
=> chore: Fix snippets for ios

v2/contribute/decisions/dashboard/0001-architecture-choice.mdx
=> chore: Add adr for dashboard

v2/emailpassword/custom-ui/init/dashboard.mdx, v2/emailpassword/pre-built-ui/setup/dashboard.mdx, v2/passwordless/custom-ui/init/dashboard.mdx, v2/passwordless/pre-built-ui/setup/dashboard.mdx, v2/thirdparty/custom-ui/init/dashboard.mdx, v2/thirdparty/pre-built-ui/setup/dashboard.mdx, v2/thirdpartyemailpassword/custom-ui/init/dashboard.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/dashboard.mdx, v2/thirdpartypasswordless/custom-ui/init/dashboard.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/dashboard.mdx, v2/userdashboard/about.mdx
=> chore: Refactor content for user management dashboard

v2/HOW_TO_NEW_DOCS.md, v2/community/sdks.mdx
=> chore: Add ios reference link for sdk docs

v2/community/sdks.mdx
=> chore: Add android to sdk refrence page

v2/contribute/checklists/saas/tables-to-consider-for-data-migration-dev-to-prod.md, v2/contribute/sidebars.js
- saas checklist added:
- tables to consider when moving data from dev to prod for user
=> Tables to consider when moving data from dev to prod for user

v2/emailpassword/migration/account-creation/ep-migration-without-password-hash.mdx, v2/emailpassword/migration/account-creation/user-creation.mdx, v2/emailpassword/sidebars.js, v2/thirdpartyemailpassword/migration/account-creation/ep-migration-without-password-hash.mdx, v2/thirdpartyemailpassword/migration/account-creation/user-creation.mdx, v2/thirdpartyemailpassword/sidebars.js
=> Update migration docs for user migration without password hashes

v2/emailpassword/migration/account-creation/ep-migration-without-password-hash.mdx, v2/thirdpartyemailpassword/migration/account-creation/ep-migration-without-password-hash.mdx
=> fixes issue in migration docs

v2/contribute/checklists/saas/move-to-aurora-serverless.md, v2/contribute/sidebars.js
- checklist regarding what to do once we deploy aurora serverless clusters in all regions
=> checklist for aurora serverless

v2/microservice_auth/jwt-creation.mdx
=> writing error

v2/passwordless/nextjs/session-verification/in-api.mdx, v2/passwordless/nextjs/setting-up-backend.mdx
Updated a couple of dead links after they have changed from js to ts
N/A
None
=> Fixing dead links

v2/emailpassword/migration/account-creation/ep-migration-without-password-hash.mdx, v2/thirdpartyemailpassword/migration/account-creation/ep-migration-without-password-hash.mdx
=> Updates migration guide snippets

v2/contribute/decisions/multitenancy/0012-how-to-pass-tenant-id-to-backend.mdx, v2/contribute/sidebars.js
=> ADR - how to pass tenant id to backend

v2/contribute/decisions/session/0006-token-header-names-follow-cookie-names.mdx, v2/contribute/decisions/session/0007-session-verification-should-allow-fallback.mdx, v2/contribute/decisions/session/0015-jwt-compatibility.mdx, v2/contribute/decisions/session/0021-handshake-after-jwt-access-token.mdx, v2/contribute/decisions/session/0022-ssr-jwt-use-case.mdx, v2/contribute/decisions/session/0023-jwks-endpoint.mdx, v2/contribute/decisions/session/0024-access-tokenstandard-jwt-claims.mdx, v2/contribute/decisions/session/0025-access-token-and-jwt-signing-keys.mdx, v2/contribute/decisions/session/0026-access-token-version-cdi.mdx, v2/contribute/decisions/session/0027-use-standard-jwt-verification-lib-on-BE.mdx, v2/contribute/decisions/session/0028-user-set-auth-header.mdx, v2/contribute/decisions/session/0029-static-and-dynamic-jwks.mdx, v2/contribute/decisions/session/0030-get-session-from-string.mdx, v2/contribute/sidebars.js
Added discussions on jwt access tokens
-
=> adr: adding this weeks discussions on jwt access tokens

v2/thirdparty/custom-ui/thirdparty-login.mdx, v2/thirdpartyemailpassword/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/custom-ui/thirdparty-login.mdx
- Adds docs for sign in with apple for iOS native
- Adds information about using the PKCE flow for mobile apps
-
=> chore: Add docs for social login with native mobile apps

v2/emailpassword/nextjs/setting-up-frontend.mdx, v2/passwordless/nextjs/setting-up-frontend.mdx, v2/thirdparty/nextjs/setting-up-frontend.mdx, v2/thirdpartyemailpassword/nextjs/setting-up-frontend.mdx, v2/thirdpartypasswordless/nextjs/setting-up-frontend.mdx
Add proper typing for nextjs dynamic import
=> fix: nextjs dynamic import ts issue

v2/docusaurus.config.js, v2/src/theme/CodeBlock/index.js, v2/src/theme/CodeBlock/styles.module.css
Swizzled the `CodeBlock` component to fix the firefox copy issue
- #571
=> fix: Added firefox clipboard fix

v2/emailpassword/common-customizations/sessions/token-transfer-method.mdx, v2/emailpassword/custom-ui/handling-session-tokens.mdx, v2/passwordless/common-customizations/sessions/token-transfer-method.mdx, v2/passwordless/custom-ui/handling-session-tokens.mdx, v2/session/common-customizations/sessions/token-transfer-method.mdx, v2/thirdparty/common-customizations/sessions/token-transfer-method.mdx, v2/thirdparty/custom-ui/handling-session-tokens.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/token-transfer-method.mdx, v2/thirdpartyemailpassword/custom-ui/handling-session-tokens.mdx, v2/thirdpartypasswordless/common-customizations/sessions/token-transfer-method.mdx, v2/thirdpartypasswordless/custom-ui/handling-session-tokens.mdx
- Update handling session tokens snippets to use headers
- Update token transfer method snippets to include a step for enabling cookies
=> chore: Fix snippets with CookieManager for Android

v2/emailpassword/common-customizations/sessions/token-transfer-method.mdx, v2/passwordless/common-customizations/sessions/token-transfer-method.mdx, v2/session/common-customizations/sessions/token-transfer-method.mdx, v2/thirdparty/common-customizations/sessions/token-transfer-method.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/token-transfer-method.mdx, v2/thirdpartypasswordless/common-customizations/sessions/token-transfer-method.mdx
=> chore: Python golang snippets for token transfer method

.circleci/config.yml
=> fix: Update circleci for flutter type checking

.circleci/config.yml
=> fix: Update circleci

.circleci/config.yml
=> fix: Update flutter paths for circle ci

v2/session/serverless/with-netlify/frontend.mdx
=> test: Changes to test code type checking for flutter

v2/session/serverless/with-netlify/frontend.mdx
=> chore: Reset code snippet for Flutter to fix typing

v2/emailpassword/nextjs/init.mdx, v2/emailpassword/pre-built-ui/setup/frontend.mdx, v2/passwordless/nextjs/init.mdx, v2/passwordless/pre-built-ui/setup/frontend.mdx, v2/src/components/tabs/NpmVersionOrYarnSubTabs.tsx, v2/thirdparty/nextjs/init.mdx, v2/thirdparty/pre-built-ui/setup/frontend.mdx, v2/thirdpartyemailpassword/nextjs/init.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/frontend.mdx, v2/thirdpartypasswordless/nextjs/init.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/frontend.mdx
add info about yarn and npmv6 installs
- Problems about missing deps on discord
=> add info about yarn and npmv6 installs

v2/session/advanced-customizations/frontend-hooks/handle-event.mdx, v2/session/advanced-customizations/frontend-hooks/pre-api.mdx
- Adds pre api hook docs for android, ios and flutter
- Adds event handler hook docs for android, ios and flutter
=> chore: Add docs for frontend hooks for mobile SDKs

v2/community/database-setup/mysql.mdx, v2/community/database-setup/postgresql.mdx, v2/emailpassword/custom-ui/init/database-setup/mysql.mdx, v2/emailpassword/custom-ui/init/database-setup/postgresql.mdx, v2/emailpassword/pre-built-ui/setup/database-setup/mysql.mdx, v2/emailpassword/pre-built-ui/setup/database-setup/postgresql.mdx, v2/passwordless/custom-ui/init/database-setup/mysql.mdx, v2/passwordless/custom-ui/init/database-setup/postgresql.mdx, v2/passwordless/pre-built-ui/setup/database-setup/mysql.mdx, v2/passwordless/pre-built-ui/setup/database-setup/postgresql.mdx, v2/session/quick-setup/database-setup/mysql.mdx, v2/session/quick-setup/database-setup/postgresql.mdx, v2/thirdparty/custom-ui/init/database-setup/mysql.mdx, v2/thirdparty/custom-ui/init/database-setup/postgresql.mdx, v2/thirdparty/pre-built-ui/setup/database-setup/mysql.mdx, v2/thirdparty/pre-built-ui/setup/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/custom-ui/init/database-setup/mysql.mdx, v2/thirdpartyemailpassword/custom-ui/init/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/database-setup/mysql.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/database-setup/postgresql.mdx, v2/thirdpartypasswordless/custom-ui/init/database-setup/mysql.mdx, v2/thirdpartypasswordless/custom-ui/init/database-setup/postgresql.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/database-setup/mysql.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/database-setup/postgresql.mdx
=> chore: updates db schema

v2/community/sdks.mdx, v2/emailpassword/sdks.mdx, v2/passwordless/sdks.mdx, v2/session/sdks.mdx, v2/thirdparty/sdks.mdx, v2/thirdpartyemailpassword/sdks.mdx, v2/thirdpartypasswordless/sdks.mdx
=> chore: Add flutter SDK to references page

v2/src/components/recipeBoxes/recipeBox.css, v2/src/css/custom.css, v2/src/theme/NavbarItem/recipeSelector.js
=> fix: height mismatch with design fixed

v2/src/theme/NavbarItem/recipeSelector.js
=> fix: recipe name fix

v2/emailpassword/custom-ui/init/dashboard.mdx, v2/emailpassword/pre-built-ui/setup/dashboard.mdx, v2/passwordless/custom-ui/init/dashboard.mdx, v2/passwordless/pre-built-ui/setup/dashboard.mdx, v2/thirdparty/custom-ui/init/dashboard.mdx, v2/thirdparty/pre-built-ui/setup/dashboard.mdx, v2/thirdpartyemailpassword/custom-ui/init/dashboard.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/dashboard.mdx, v2/thirdpartypasswordless/custom-ui/init/dashboard.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/dashboard.mdx, v2/userdashboard/about.mdx
- Fix indentation for golang snippets in user dashboard docs
- Update CSP headers required for user dashboard
-
=> fix: Fix dashboard snippets

v2/community/database-setup/mysql.mdx, v2/community/database-setup/postgresql.mdx, v2/emailpassword/custom-ui/init/database-setup/mysql.mdx, v2/emailpassword/custom-ui/init/database-setup/postgresql.mdx, v2/emailpassword/pre-built-ui/setup/database-setup/mysql.mdx, v2/emailpassword/pre-built-ui/setup/database-setup/postgresql.mdx, v2/passwordless/custom-ui/init/database-setup/mysql.mdx, v2/passwordless/custom-ui/init/database-setup/postgresql.mdx, v2/passwordless/pre-built-ui/setup/database-setup/mysql.mdx, v2/passwordless/pre-built-ui/setup/database-setup/postgresql.mdx, v2/session/quick-setup/database-setup/mysql.mdx, v2/session/quick-setup/database-setup/postgresql.mdx, v2/thirdparty/custom-ui/init/database-setup/mysql.mdx, v2/thirdparty/custom-ui/init/database-setup/postgresql.mdx, v2/thirdparty/pre-built-ui/setup/database-setup/mysql.mdx, v2/thirdparty/pre-built-ui/setup/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/custom-ui/init/database-setup/mysql.mdx, v2/thirdpartyemailpassword/custom-ui/init/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/database-setup/mysql.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/database-setup/postgresql.mdx, v2/thirdpartypasswordless/custom-ui/init/database-setup/mysql.mdx, v2/thirdpartypasswordless/custom-ui/init/database-setup/postgresql.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/database-setup/mysql.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/database-setup/postgresql.mdx
Add tables for active users feature and TOTP recipe
- https://github.com/supertokens/supertokens-core/issues/597
=> feat: Add tables for active users feature and TOTP recipe

v2/community/supertokens-core/self-hosted/with-docker.mdx, v2/emailpassword/custom-ui/init/core/self-hosted-with-docker.mdx, v2/emailpassword/pre-built-ui/setup/core/self-hosted-with-docker.mdx, v2/passwordless/custom-ui/init/core/self-hosted-with-docker.mdx, v2/passwordless/pre-built-ui/setup/core/self-hosted-with-docker.mdx, v2/session/quick-setup/core/self-hosted-with-docker.mdx, v2/thirdparty/custom-ui/init/core/self-hosted-with-docker.mdx, v2/thirdparty/pre-built-ui/setup/core/self-hosted-with-docker.mdx, v2/thirdpartyemailpassword/custom-ui/init/core/self-hosted-with-docker.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/core/self-hosted-with-docker.mdx, v2/thirdpartypasswordless/custom-ui/init/core/self-hosted-with-docker.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/core/self-hosted-with-docker.mdx
=> fix: updates postgres docker-compose

v2/emailpassword/migration/account-creation/user-id-mapping.mdx, v2/passwordless/migration/account-creation/user-id-mapping.mdx, v2/thirdparty/migration/account-creation/user-id-mapping.mdx, v2/thirdpartyemailpassword/migration/account-creation/user-id-mapping.mdx, v2/thirdpartypasswordless/migration/account-creation/user-id-mapping.mdx
- https://github.com/supertokens/docs/pull/636
=> chore: fix typo in migration docs

v2/emailpassword/redwood/about.mdx, v2/passwordless/redwood/about.mdx, v2/thirdparty/redwood/about.mdx, v2/thirdpartyemailpassword/redwood/about.mdx, v2/thirdpartypasswordless/redwood/about.mdx
=> Link to redwood setup docs

v2/community/database-setup/postgresql.mdx, v2/emailpassword/custom-ui/init/database-setup/postgresql.mdx, v2/emailpassword/pre-built-ui/setup/database-setup/postgresql.mdx, v2/passwordless/custom-ui/init/database-setup/postgresql.mdx, v2/passwordless/pre-built-ui/setup/database-setup/postgresql.mdx, v2/session/quick-setup/database-setup/postgresql.mdx, v2/thirdparty/custom-ui/init/database-setup/postgresql.mdx, v2/thirdparty/pre-built-ui/setup/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/custom-ui/init/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/database-setup/postgresql.mdx, v2/thirdpartypasswordless/custom-ui/init/database-setup/postgresql.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/database-setup/postgresql.mdx
Update documentation by removing `BIGINT` modifier
#640
N/A
=> #640 Remove BIGINT from PostgreSQL initialization documentation

v2/emailpassword/advanced-customizations/frontend-hooks/pre-api.mdx, v2/passwordless/advanced-customizations/frontend-hooks/pre-api.mdx, v2/thirdparty/advanced-customizations/frontend-hooks/pre-api.mdx, v2/thirdpartyemailpassword/advanced-customizations/frontend-hooks/pre-api.mdx, v2/thirdpartypasswordless/advanced-customizations/frontend-hooks/pre-api.mdx
=> Updates pre api hook docs

v2/emailpassword/advanced-customizations/frontend-hooks/pre-api.mdx, v2/passwordless/advanced-customizations/frontend-hooks/pre-api.mdx, v2/thirdparty/advanced-customizations/frontend-hooks/pre-api.mdx, v2/thirdpartyemailpassword/advanced-customizations/frontend-hooks/pre-api.mdx, v2/thirdpartypasswordless/advanced-customizations/frontend-hooks/pre-api.mdx
=> fix: update iOS snippets

v2/emailpassword/common-customizations/change-password.mdx, v2/emailpassword/common-customizations/disable-sign-up/emailpassword-changes.mdx, v2/thirdpartyemailpassword/common-customizations/change-password.mdx, v2/thirdpartyemailpassword/common-customizations/disable-sign-up/emailpassword-changes.mdx
=> fix: Update `updateEmailOrPassword` to mention custom password validation policies are not applied

v2/emailpassword/common-customizations/change-password.mdx, v2/emailpassword/common-customizations/disable-sign-up/emailpassword-changes.mdx, v2/thirdpartyemailpassword/common-customizations/disable-sign-up/emailpassword-changes.mdx
=> fix failing disable signup snippets

v2/emailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/emailpassword/common-customizations/sessions/claims/claim-validators.mdx, v2/emailpassword/common-customizations/sessions/protecting-frontend-routes.mdx, v2/emailpassword/user-roles/protecting-routes.mdx, v2/mfa/pre-built-ui/showing-login-ui.mdx, v2/passwordless/common-customizations/email-verification/protecting-routes.mdx, v2/passwordless/common-customizations/sessions/claims/claim-validators.mdx, v2/passwordless/common-customizations/sessions/protecting-frontend-routes.mdx, v2/passwordless/user-roles/protecting-routes.mdx, v2/session/common-customizations/sessions/claims/claim-validators.mdx, v2/session/common-customizations/sessions/protecting-frontend-routes.mdx, v2/src/plugins/codeTypeChecking/jsEnv/package.json, v2/thirdparty/common-customizations/email-verification/protecting-routes.mdx, v2/thirdparty/common-customizations/sessions/claims/claim-validators.mdx, v2/thirdparty/common-customizations/sessions/protecting-frontend-routes.mdx, v2/thirdparty/user-roles/protecting-routes.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/claims/claim-validators.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/protecting-frontend-routes.mdx, v2/thirdpartyemailpassword/user-roles/protecting-routes.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartypasswordless/common-customizations/sessions/claims/claim-validators.mdx, v2/thirdpartypasswordless/common-customizations/sessions/protecting-frontend-routes.mdx, v2/thirdpartypasswordless/user-roles/protecting-routes.mdx, v2/userroles/protecting-routes.mdx
=> fix: docs & update ts version

v2/emailpassword/common-customizations/email-verification/about.mdx, v2/emailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/emailpassword/pre-built-ui/enable-email-verification.mdx, v2/passwordless/common-customizations/email-verification/about.mdx, v2/passwordless/common-customizations/email-verification/protecting-routes.mdx, v2/passwordless/pre-built-ui/enable-email-verification.mdx, v2/thirdparty/common-customizations/email-verification/about.mdx, v2/thirdparty/common-customizations/email-verification/protecting-routes.mdx, v2/thirdparty/pre-built-ui/enable-email-verification.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/about.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartyemailpassword/pre-built-ui/enable-email-verification.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/about.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartypasswordless/pre-built-ui/enable-email-verification.mdx
=> chore: adds more email verification docs

v2/contribute/architecture/recipes.mdx, v2/emailpassword/common-customizations/delete-user.mdx, v2/emailpassword/common-customizations/email-verification/about.mdx, v2/emailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/emailpassword/custom-ui/enable-email-verification.mdx, v2/emailpassword/email-delivery/smtp/configure-smtp.mdx, v2/emailpassword/pre-built-ui/enable-email-verification.mdx, v2/passwordless/common-customizations/email-verification/about.mdx, v2/passwordless/common-customizations/email-verification/protecting-routes.mdx, v2/passwordless/custom-ui/enable-email-verification.mdx, v2/passwordless/pre-built-ui/enable-email-verification.mdx, v2/thirdparty/common-customizations/delete-user.mdx, v2/thirdparty/common-customizations/email-verification/about.mdx, v2/thirdparty/common-customizations/email-verification/protecting-routes.mdx, v2/thirdparty/custom-ui/enable-email-verification.mdx, v2/thirdparty/email-delivery/smtp/configure-smtp.mdx, v2/thirdparty/pre-built-ui/enable-email-verification.mdx, v2/thirdpartyemailpassword/common-customizations/delete-user.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/about.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartyemailpassword/custom-ui/enable-email-verification.mdx, v2/thirdpartyemailpassword/email-delivery/smtp/configure-smtp.mdx, v2/thirdpartyemailpassword/pre-built-ui/enable-email-verification.mdx, v2/thirdpartypasswordless/common-customizations/delete-user.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/about.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartypasswordless/custom-ui/enable-email-verification.mdx, v2/thirdpartypasswordless/email-delivery/smtp/configure-smtp.mdx, v2/thirdpartypasswordless/pre-built-ui/enable-email-verification.mdx
=> Email verification updates

v2/emailpassword/common-customizations/email-verification/about.mdx, v2/emailpassword/custom-ui/enable-email-verification.mdx, v2/emailpassword/pre-built-ui/enable-email-verification.mdx, v2/passwordless/common-customizations/email-verification/about.mdx, v2/passwordless/custom-ui/enable-email-verification.mdx, v2/passwordless/pre-built-ui/enable-email-verification.mdx, v2/thirdparty/common-customizations/email-verification/about.mdx, v2/thirdparty/custom-ui/enable-email-verification.mdx, v2/thirdparty/pre-built-ui/enable-email-verification.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/about.mdx, v2/thirdpartyemailpassword/custom-ui/enable-email-verification.mdx, v2/thirdpartyemailpassword/pre-built-ui/enable-email-verification.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/about.mdx, v2/thirdpartypasswordless/custom-ui/enable-email-verification.mdx, v2/thirdpartypasswordless/pre-built-ui/enable-email-verification.mdx
=> chore: adds missing emailverification docs

v2/emailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/emailpassword/custom-ui/enable-email-verification.mdx, v2/passwordless/common-customizations/email-verification/protecting-routes.mdx, v2/passwordless/custom-ui/enable-email-verification.mdx, v2/thirdparty/common-customizations/email-verification/protecting-routes.mdx, v2/thirdparty/custom-ui/enable-email-verification.mdx, v2/thirdpartyemailpassword/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartyemailpassword/custom-ui/enable-email-verification.mdx, v2/thirdpartypasswordless/common-customizations/email-verification/protecting-routes.mdx, v2/thirdpartypasswordless/custom-ui/enable-email-verification.mdx
=> Adds missing email verification snippet

v2/emailpassword/migration/account-creation/user-creation.mdx, v2/thirdparty/custom-ui/init/backend.mdx, v2/thirdparty/pre-built-ui/setup/backend.mdx, v2/thirdpartyemailpassword/custom-ui/init/backend.mdx, v2/thirdpartyemailpassword/migration/account-creation/user-creation.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/backend.mdx, v2/thirdpartypasswordless/custom-ui/init/backend.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/backend.mdx
=> chore: improves migration and tp setup docs

v2/emailpassword/custom-ui/init/dashboard.mdx, v2/emailpassword/pre-built-ui/setup/dashboard.mdx, v2/passwordless/custom-ui/init/dashboard.mdx, v2/passwordless/pre-built-ui/setup/dashboard.mdx, v2/thirdparty/custom-ui/init/dashboard.mdx, v2/thirdparty/pre-built-ui/setup/dashboard.mdx, v2/thirdpartyemailpassword/custom-ui/init/dashboard.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/dashboard.mdx, v2/thirdpartypasswordless/custom-ui/init/dashboard.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/dashboard.mdx, v2/userdashboard/about.mdx
- Updates the copy for user dashboard to mention that 3 dashboard users can be created for free
=> Update free users copy for user dashboard

v2/src/components/appInfoForm/index.tsx
=> fix: Fix label styling for next js app info form

v2/emailpassword/common-customizations/change-email-post-login.mdx, v2/emailpassword/sidebars.js, v2/thirdpartyemailpassword/common-customizations/change-email-post-login.mdx, v2/thirdpartyemailpassword/sidebars.js
=> chore: adds guide for updating email post login

v2/emailpassword/common-customizations/change-email-post-login.mdx, v2/thirdpartyemailpassword/common-customizations/change-email-post-login.mdx
=> fix: updates python snippets

v2/emailpassword/common-customizations/sessions/anonymous-session.mdx, v2/emailpassword/common-customizations/sessions/with-jwt/jwt-verification.mdx, v2/passwordless/common-customizations/sessions/anonymous-session.mdx, v2/passwordless/common-customizations/sessions/with-jwt/jwt-verification.mdx, v2/session/common-customizations/sessions/anonymous-session.mdx, v2/session/common-customizations/sessions/with-jwt/jwt-verification.mdx, v2/thirdparty/common-customizations/sessions/anonymous-session.mdx, v2/thirdparty/common-customizations/sessions/with-jwt/jwt-verification.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/anonymous-session.mdx, v2/thirdpartyemailpassword/common-customizations/sessions/with-jwt/jwt-verification.mdx, v2/thirdpartypasswordless/common-customizations/sessions/anonymous-session.mdx, v2/thirdpartypasswordless/common-customizations/sessions/with-jwt/jwt-verification.mdx
=> chore: update JWT verification and anonymous session docs

v2/community/reusableMD/intro-architecture.mdx, v2/src/components/tabs/BackendSDKTabs.tsx
=> chore: changes to other framework snippet and docs

v2/src/plugins/codeTypeChecking/iosenv/iosenv.xcodeproj/project.pbxproj, v2/thirdparty/custom-ui/thirdparty-login.mdx, v2/thirdpartyemailpassword/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/custom-ui/thirdparty-login.mdx
=> fix: Fix ios snippets for third party login using auth code flow

v2/community/database-setup/mysql.mdx, v2/community/database-setup/postgresql.mdx, v2/emailpassword/custom-ui/init/database-setup/mysql.mdx, v2/emailpassword/custom-ui/init/database-setup/postgresql.mdx, v2/emailpassword/pre-built-ui/setup/database-setup/mysql.mdx, v2/emailpassword/pre-built-ui/setup/database-setup/postgresql.mdx, v2/passwordless/custom-ui/init/database-setup/mysql.mdx, v2/passwordless/custom-ui/init/database-setup/postgresql.mdx, v2/passwordless/pre-built-ui/setup/database-setup/mysql.mdx, v2/passwordless/pre-built-ui/setup/database-setup/postgresql.mdx, v2/session/quick-setup/database-setup/mysql.mdx, v2/session/quick-setup/database-setup/postgresql.mdx, v2/thirdparty/custom-ui/init/database-setup/mysql.mdx, v2/thirdparty/custom-ui/init/database-setup/postgresql.mdx, v2/thirdparty/pre-built-ui/setup/database-setup/mysql.mdx, v2/thirdparty/pre-built-ui/setup/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/custom-ui/init/database-setup/mysql.mdx, v2/thirdpartyemailpassword/custom-ui/init/database-setup/postgresql.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/database-setup/mysql.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/database-setup/postgresql.mdx, v2/thirdpartypasswordless/custom-ui/init/database-setup/mysql.mdx, v2/thirdpartypasswordless/custom-ui/init/database-setup/postgresql.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/database-setup/mysql.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/database-setup/postgresql.mdx
=> fix: schema updates

v2/thirdparty/custom-ui/thirdparty-login.mdx, v2/thirdpartyemailpassword/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/custom-ui/thirdparty-login.mdx
=> chore: Fix ios snippets

v2/thirdparty/custom-ui/thirdparty-login.mdx, v2/thirdpartyemailpassword/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/custom-ui/thirdparty-login.mdx
=> chore: Ios snippets fix

v2/multitenancy/introduction.mdx, v2/passwordless/introduction.mdx, v2/thirdparty/introduction.mdx, v2/thirdpartyemailpassword/introduction.mdx, v2/thirdpartypasswordless/introduction.mdx
=> adds links to feature pages

v2/multitenancy/introduction.mdx, v2/passwordless/introduction.mdx, v2/thirdparty/introduction.mdx, v2/thirdpartyemailpassword/introduction.mdx, v2/thirdpartypasswordless/introduction.mdx
=> adds feature page links

v2/src/plugins/codeTypeChecking/dart_env/pubspec.lock, v2/src/plugins/codeTypeChecking/dart_env/pubspec.yaml, v2/thirdparty/custom-ui/thirdparty-login.mdx, v2/thirdpartyemailpassword/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/custom-ui/thirdparty-login.mdx
- Adds flutter snippets for social login
-
=> chore: Add social login snippets for flutter

v2/src/css/custom.css, v2/src/plugins/codeTypeChecking/jsEnv/package.json
=> fix: scroll recipe dropdown list in smaller height screens

v2/src/components/recipeBoxes/recipeLayout.css
=> fix: auth methods card aligments in small screens

v2/community/reusableMD/multitenancy/MultiTenancyPaidBanner.mdx, v2/emailpassword/custom-ui/init/dashboard.mdx, v2/emailpassword/pre-built-ui/setup/dashboard.mdx, v2/passwordless/custom-ui/init/dashboard.mdx, v2/passwordless/pre-built-ui/setup/dashboard.mdx, v2/thirdparty/custom-ui/init/dashboard.mdx, v2/thirdparty/pre-built-ui/setup/dashboard.mdx, v2/thirdpartyemailpassword/custom-ui/init/dashboard.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/dashboard.mdx, v2/thirdpartypasswordless/custom-ui/init/dashboard.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/dashboard.mdx, v2/userdashboard/about.mdx
- Updates the paid feature admonition for user dashboard and multitenancy
- ...
=> Change paid feature admonition to mention generating license keys

v2/emailpassword/custom-ui/init/dashboard.mdx, v2/emailpassword/pre-built-ui/setup/dashboard.mdx, v2/passwordless/custom-ui/init/dashboard.mdx, v2/passwordless/pre-built-ui/setup/dashboard.mdx, v2/thirdparty/custom-ui/init/dashboard.mdx, v2/thirdparty/pre-built-ui/setup/dashboard.mdx, v2/thirdpartyemailpassword/custom-ui/init/dashboard.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/dashboard.mdx, v2/thirdpartypasswordless/custom-ui/init/dashboard.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/dashboard.mdx, v2/userdashboard/about.mdx
=> fix: Fix broken link

v2/thirdparty/custom-ui/init/backend.mdx, v2/thirdparty/pre-built-ui/setup/backend.mdx, v2/thirdpartyemailpassword/custom-ui/init/backend.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/backend.mdx, v2/thirdpartyemailpassword/serverless/with-aws-lambda/backend-config.mdx, v2/thirdpartypasswordless/custom-ui/init/backend.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/backend.mdx
Fixes the keys of additional config for Apple clients in golang and python code snippets
=> fix: Fix apple snippets for golang and python

v2/emailpassword/custom-ui/init/dashboard.mdx, v2/emailpassword/pre-built-ui/setup/dashboard.mdx, v2/passwordless/custom-ui/init/dashboard.mdx, v2/passwordless/pre-built-ui/setup/dashboard.mdx, v2/src/plugins/codeTypeChecking/goEnv/go.mod, v2/src/plugins/codeTypeChecking/goEnv/go.sum, v2/src/plugins/codeTypeChecking/jsEnv/package.json, v2/src/plugins/codeTypeChecking/pythonEnv/requirements.txt, v2/thirdparty/custom-ui/init/dashboard.mdx, v2/thirdparty/pre-built-ui/setup/dashboard.mdx, v2/thirdpartyemailpassword/custom-ui/init/dashboard.mdx, v2/thirdpartyemailpassword/pre-built-ui/setup/dashboard.mdx, v2/thirdpartypasswordless/custom-ui/init/dashboard.mdx, v2/thirdpartypasswordless/pre-built-ui/setup/dashboard.mdx, v2/userdashboard/about.mdx
=> Add docs explaining how to manage access for user dashboard users

v2/emailpassword/custom-ui/init/frontend.mdx, v2/passwordless/custom-ui/init/frontend.mdx, v2/session/quick-setup/frontend.mdx, v2/thirdparty/custom-ui/init/frontend.mdx, v2/thirdpartyemailpassword/custom-ui/init/frontend.mdx, v2/thirdpartypasswordless/custom-ui/init/frontend.mdx
=> Add setup step for swift package manager

.github/workflows/versioning.yml
=> feat: Add github workflow for versioning

v2/src/theme/TOC/index.js
=> Use location hook instead of window during rendering

v2/src/plugins/codeTypeChecking/goEnv/go.mod, v2/src/plugins/codeTypeChecking/jsEnv/package.json, v2/src/theme/TOC/index.js, v2/thirdparty/common-customizations/sign-in-and-up/built-in-providers.mdx, v2/thirdparty/common-customizations/sign-in-and-up/provider-config.mdx, v2/thirdpartyemailpassword/common-customizations/sign-in-and-up/provider-config.mdx, v2/thirdpartyemailpassword/common-customizations/signup-form/built-in-providers.mdx, v2/thirdpartypasswordless/common-customizations/sign-in-and-up/provider-config.mdx, v2/thirdpartypasswordless/common-customizations/signup-form/built-in-providers.mdx
=> Add docs for Twitter provider

CONTRIBUTING.md
=> chore: Update CONTRIBUTING

v2/community/versioning.mdx
=> Update versioning to mention node 16

v2/emailpassword/custom-ui/email-password-login.mdx, v2/thirdparty/custom-ui/thirdparty-login.mdx, v2/thirdpartyemailpassword/custom-ui/email-password-login.mdx, v2/thirdpartyemailpassword/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/custom-ui/thirdparty-login.mdx
=> Add explanation for Flutter social login with Apple on Android

v2/thirdparty/custom-ui/thirdparty-login.mdx, v2/thirdpartyemailpassword/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/custom-ui/thirdparty-login.mdx
=> Fix apple sign in snippets

v2/thirdparty/custom-ui/thirdparty-login.mdx, v2/thirdpartyemailpassword/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/custom-ui/thirdparty-login.mdx
=> Fix python snippets for apple login

v2/emailpassword/common-customizations/core/add-ssl-via-nginx.mdx, v2/passwordless/common-customizations/core/add-ssl-via-nginx.mdx, v2/session/common-customizations/core/add-ssl-via-nginx.mdx, v2/thirdparty/common-customizations/core/add-ssl-via-nginx.mdx, v2/thirdpartyemailpassword/common-customizations/core/add-ssl-via-nginx.mdx, v2/thirdpartypasswordless/common-customizations/core/add-ssl-via-nginx.mdx
=> fix command to create SSL certificates

v2/docusaurus.config.js, v2/src/plugins/locationInterceptor.js
added client-side interceptor to fire page view analytics.
=> feat: intercept client-side navigation.

v2/emailpassword/nextjs/app-directory/protecting-route.mdx, v2/emailpassword/nextjs/app-directory/server-components-requests.mdx, v2/passwordless/nextjs/app-directory/protecting-route.mdx, v2/passwordless/nextjs/app-directory/server-components-requests.mdx, v2/thirdparty/nextjs/app-directory/protecting-route.mdx, v2/thirdparty/nextjs/app-directory/server-components-requests.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/protecting-route.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/server-components-requests.mdx, v2/thirdpartypasswordless/nextjs/app-directory/protecting-route.mdx, v2/thirdpartypasswordless/nextjs/app-directory/server-components-requests.mdx
=> Add custom ui snippets for next integration docs with app directory

v2/thirdparty/common-customizations/sessions/session-verification-in-api/overview.mdx
=> Update overview.mdx fix typo

v2/emailpassword/nextjs/app-directory/init.mdx, v2/passwordless/nextjs/app-directory/init.mdx, v2/thirdparty/nextjs/app-directory/init.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/init.mdx, v2/thirdpartypasswordless/nextjs/app-directory/init.mdx
=> Add framework custom for next app dir

v2/emailpassword/nextjs/app-directory/init.mdx, v2/passwordless/nextjs/app-directory/init.mdx, v2/thirdparty/nextjs/app-directory/init.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/init.mdx, v2/thirdpartypasswordless/nextjs/app-directory/init.mdx
=> Resolve issues in next docs

v2/thirdpartyemailpassword/introduction.mdx
=> Typo introduction.mdx

v2/emailpassword/nextjs/app-directory/protecting-route.mdx, v2/passwordless/nextjs/app-directory/protecting-route.mdx, v2/thirdparty/custom-ui/thirdparty-login.mdx, v2/thirdparty/nextjs/app-directory/protecting-route.mdx, v2/thirdpartyemailpassword/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/custom-ui/thirdparty-login.mdx, v2/thirdpartypasswordless/nextjs/app-directory/protecting-route.mdx
=> Update explanation for Android google login

v2/thirdpartypasswordless/serverless/with-aws-lambda/backend-config.mdx
Fixes AWS lambda backend config snippets, previously values were hardcoded instead of using the form variables.
=> fix: AWS lambda backend config code snippet

v2/emailpassword/custom-ui/handling-session-tokens.mdx, v2/passwordless/custom-ui/handling-session-tokens.mdx, v2/session/quick-setup/handling-session-tokens.mdx, v2/src/plugins/codeTypeChecking/dart_env/pubspec.lock, v2/src/plugins/codeTypeChecking/dart_env/pubspec.yaml, v2/thirdparty/custom-ui/handling-session-tokens.mdx, v2/thirdpartyemailpassword/custom-ui/handling-session-tokens.mdx, v2/thirdpartypasswordless/custom-ui/handling-session-tokens.mdx
=> Add snippets for using session tokens with Flutter

v2/emailpassword/custom-ui/handling-session-tokens.mdx, v2/passwordless/custom-ui/handling-session-tokens.mdx, v2/session/quick-setup/handling-session-tokens.mdx, v2/src/plugins/codeTypeChecking/dart_env/pubspec.lock, v2/src/plugins/codeTypeChecking/dart_env/pubspec.yaml, v2/thirdparty/custom-ui/handling-session-tokens.mdx, v2/thirdpartyemailpassword/custom-ui/handling-session-tokens.mdx, v2/thirdpartypasswordless/custom-ui/handling-session-tokens.mdx
=> Fix flutter code type checking

v2/src/components/compatibility/CompatibilitySelect.tsx, v2/src/components/compatibility/index.tsx, v2/src/components/compatibility/style.css, v2/static/img/arrow-down.svg
Replaced custom select compnent with native select element.
=> fix: use native select element.

v2/emailpassword/nextjs/app-directory/init.mdx, v2/emailpassword/nextjs/app-directory/protecting-route.mdx, v2/emailpassword/nextjs/app-directory/server-components-requests.mdx, v2/emailpassword/nextjs/app-directory/session-verification-middleware.mdx, v2/emailpassword/nextjs/app-directory/session-verification-session-guard.mdx, v2/emailpassword/nextjs/app-directory/setting-up-backend.mdx, v2/passwordless/nextjs/app-directory/init.mdx, v2/passwordless/nextjs/app-directory/protecting-route.mdx, v2/passwordless/nextjs/app-directory/server-components-requests.mdx, v2/passwordless/nextjs/app-directory/session-verification-middleware.mdx, v2/passwordless/nextjs/app-directory/session-verification-session-guard.mdx, v2/passwordless/nextjs/app-directory/setting-up-backend.mdx, v2/thirdparty/nextjs/app-directory/init.mdx, v2/thirdparty/nextjs/app-directory/protecting-route.mdx, v2/thirdparty/nextjs/app-directory/server-components-requests.mdx, v2/thirdparty/nextjs/app-directory/session-verification-middleware.mdx, v2/thirdparty/nextjs/app-directory/session-verification-session-guard.mdx, v2/thirdparty/nextjs/app-directory/setting-up-backend.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/init.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/protecting-route.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/server-components-requests.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/session-verification-middleware.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/session-verification-session-guard.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/setting-up-backend.mdx, v2/thirdpartypasswordless/nextjs/app-directory/init.mdx, v2/thirdpartypasswordless/nextjs/app-directory/protecting-route.mdx, v2/thirdpartypasswordless/nextjs/app-directory/server-components-requests.mdx, v2/thirdpartypasswordless/nextjs/app-directory/session-verification-middleware.mdx, v2/thirdpartypasswordless/nextjs/app-directory/session-verification-session-guard.mdx, v2/thirdpartypasswordless/nextjs/app-directory/setting-up-backend.mdx
Fixes issues in Next.js app dir docs.
=> fix: Next.js app dir docs

v2/emailpassword/email-delivery/smtp/configure-smtp.mdx, v2/passwordless/email-delivery/smtp/configure-smtp.mdx, v2/src/plugins/codeTypeChecking/goEnv/go.mod, v2/src/plugins/codeTypeChecking/goEnv/go.sum, v2/thirdparty/email-delivery/smtp/configure-smtp.mdx, v2/thirdpartyemailpassword/email-delivery/smtp/configure-smtp.mdx, v2/thirdpartypasswordless/email-delivery/smtp/configure-smtp.mdx
=> fix: golang smtp update

v2/emailpassword/nestjs/guide.mdx, v2/passwordless/nestjs/guide.mdx, v2/thirdparty/nestjs/guide.mdx, v2/thirdpartyemailpassword/nestjs/guide.mdx, v2/thirdpartypasswordless/nestjs/guide.mdx
I corrected an error in the NestJS guide's CORS setup section, replacing 'AuthModule' with 'AppModule'. I also corrected the relative path of an import statement.
=> Minor NestJS guide corrections

v2/emailpassword/common-customizations/handling-signup-success.mdx, v2/emailpassword/common-customizations/signup-form/adding-fields.mdx, v2/passwordless/common-customizations/handling-signinup-success.mdx, v2/passwordless/common-customizations/userid-format.mdx, v2/thirdparty/common-customizations/handling-signinup-success.mdx, v2/thirdpartyemailpassword/common-customizations/handling-signinup-success.mdx, v2/thirdpartyemailpassword/common-customizations/signup-form/adding-fields.mdx, v2/thirdpartypasswordless/common-customizations/handling-signinup-success.mdx, v2/thirdpartypasswordless/common-customizations/userid-format.mdx
Fixes a comment in the `Handle form fields on successful Sign-up` section.
=> Fix comment in python example

v2/multitenancy/architecture.mdx
=> fix: architecture.mdx typo

v2/contribute/architecture/recipes.mdx
This PR fixes the typo in recipes.mdx
=> docs: fix typo in recipes.mdx

v2/emailpassword/nextjs/app-directory/setting-up-frontend.mdx, v2/emailpassword/nextjs/setting-up-frontend.mdx, v2/mfa/email-sms-otp/otp-for-all-users.mdx, v2/mfa/frontend-setup.mdx, v2/mfa/step-up-auth.mdx, v2/passwordless/nextjs/app-directory/setting-up-frontend.mdx, v2/passwordless/nextjs/setting-up-frontend.mdx, v2/src/components/appInfoForm/index.tsx, v2/thirdparty/nextjs/app-directory/setting-up-frontend.mdx, v2/thirdparty/nextjs/setting-up-frontend.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/setting-up-frontend.mdx, v2/thirdpartyemailpassword/nextjs/setting-up-frontend.mdx, v2/thirdpartypasswordless/nextjs/app-directory/setting-up-frontend.mdx, v2/thirdpartypasswordless/nextjs/setting-up-frontend.mdx
update storybooks/chromatic links
=> update storybooks/chromatic links

v2/package-lock.json, v2/package.json, v2/src/components/tsconfig.json, v2/yarn.lock
=> updates supertokens-website version

v2/emailpassword/serverless/with-aws-lambda/authorizer.mdx, v2/passwordless/serverless/with-aws-lambda/authorizer.mdx, v2/session/serverless/with-aws-lambda/authorizer.mdx, v2/thirdparty/serverless/with-aws-lambda/authorizer.mdx, v2/thirdpartyemailpassword/serverless/with-aws-lambda/authorizer.mdx, v2/thirdpartypasswordless/serverless/with-aws-lambda/authorizer.mdx
=> fix: code type check

v2/src/components/httpNetworking.ts, v2/src/components/utils.ts, v2/src/theme/Layout/index.js
=> chore: Add meta data to sdk logs

v2/src/components/httpNetworking.ts
=> chore: Handle 401 error in desynced session

v2/src/components/httpNetworking.ts
=> Chore: Add status code to desynced_session_state payload

v2/emailpassword/common-customizations/multi-tenancy/new-tenant-config.mdx, v2/multitenancy/new-tenant.mdx, v2/passwordless/common-customizations/multi-tenancy/new-tenant-config.mdx, v2/thirdparty/common-customizations/multi-tenancy/new-tenant-config.mdx, v2/thirdpartyemailpassword/common-customizations/multi-tenancy/new-tenant-config.mdx, v2/thirdpartypasswordless/common-customizations/multi-tenancy/new-tenant-config.mdx
=> fix: new tenant pages

v2/mfa/backend-setup.mdx, v2/mfa/email-sms-otp/otp-for-all-users.mdx, v2/mfa/totp/totp-for-all-users.mdx, v2/multitenancy/new-tenant.mdx, v2/thirdparty/common-customizations/multi-tenancy/custom-provider.mdx, v2/thirdparty/common-customizations/multi-tenancy/new-tenant-config.mdx, v2/thirdparty/custom-ui/multitenant-login.mdx, v2/thirdparty/pre-built-ui/multitenant-login.mdx, v2/thirdpartyemailpassword/common-customizations/multi-tenancy/custom-provider.mdx, v2/thirdpartyemailpassword/common-customizations/multi-tenancy/new-tenant-config.mdx, v2/thirdpartyemailpassword/custom-ui/multitenant-login.mdx, v2/thirdpartyemailpassword/pre-built-ui/multitenant-login.mdx, v2/thirdpartypasswordless/common-customizations/multi-tenancy/custom-provider.mdx, v2/thirdpartypasswordless/common-customizations/multi-tenancy/new-tenant-config.mdx, v2/thirdpartypasswordless/custom-ui/multitenant-login.mdx, v2/thirdpartypasswordless/pre-built-ui/multitenant-login.mdx
- Use single / multi-app tabs everywhere
- Fixes json in curl requests
=> fix: single/multi-app selectors and json fixes

v2/emailpassword/nextjs/app-directory/about.mdx, v2/passwordless/nextjs/app-directory/about.mdx, v2/thirdparty/nextjs/app-directory/about.mdx, v2/thirdpartyemailpassword/nextjs/app-directory/about.mdx, v2/thirdpartypasswordless/nextjs/app-directory/about.mdx
Embeds recent video on integrating with nextjs
=> Add nextjs integration video.

v2/src/theme/NavbarItem/recipeSelector.js
Fixes the recipe selector component behaviour.
=> Fix recipe selector

v2/src/components/appInfoForm/index.tsx, v2/src/components/compatibility/CompatibilitySelect.tsx, v2/src/components/compatibility/index.tsx
This PR fixes two issues
- Inconsistent behaviour of the compatibility table
- Minor css issue
The compatibility table was using an uncontrolled select element, which was causing a mismatch between the selected values, and the displayed values.
https://www.loom.com/share/eae55cb688224d28ae59a1b9c7ddf347
In production, a style in the parent label (with `!important` flag), was overriding the default styles of the span.
=> Fix: Compatibility table issues + Minor css issue

v2/emailpassword/serverless/with-aws-lambda/setup-api-gateway.mdx, v2/passwordless/serverless/with-aws-lambda/setup-api-gateway.mdx, v2/session/serverless/with-aws-lambda/setup-api-gateway.mdx, v2/thirdparty/serverless/with-aws-lambda/setup-api-gateway.mdx, v2/thirdpartyemailpassword/serverless/with-aws-lambda/setup-api-gateway.mdx, v2/thirdpartypasswordless/serverless/with-aws-lambda/setup-api-gateway.mdx
=> fix: lambda

v2/passwordless/migration/account-creation/user-creation.mdx
sorry for taking your time for a typo but I'm sort of a OCD
=> docs: fix a typo in passwordless migration

v2/src/components/api/webJs.ts, v2/src/components/webJsInjector/index.tsx
Mocked the values for the test environment and made replacements work without a fixed URI object.
Tested for production by commenting out code that is for test/local and manually changed prod API URL.
Also tested locally.
=> Web-JS URI mocks for test docs

v2/attackprotectionsuite/backend-setup.mdx, v2/attackprotectionsuite/frontend-setup.mdx, v2/src/plugins/codeTypeChecking/index.js
Changed the frontend SDK import snippet to work with build systems. 
Added implementation for passwordResetPOST and cleaned up snippets
- Tested fronted snippet with a new create-react-app and with a regular html file containing the script
-
=> Attack protection suite improvements
