- emailpassword/docs/serverless/with-aws-lambda/backend-config.md
- emailpassword/docs/serverless/with-netlify/backend-config.md
- session/docs/serverless/with-aws-lambda/backend-config.md
- session/docs/serverless/with-netlify/backend-config.md
- thirdparty/docs/serverless/with-aws-lambda/backend-config.md
- thirdparty/docs/serverless/with-netlify/backend-config.md
- thirdpartyemailpassword/docs/serverless/with-aws-lambda/backend-config.md
- thirdpartyemailpassword/docs/serverless/with-netlify/backend-config.md
There were several instances of `reqiure` which wouldn't have worked.
Small PR to rectify this
> Rectify typo in NodeJS docs

- v2/session/appinfo.mdx
AppInfo page updated specifically for the sessions only recipe, since neither email/password reset links will be created and nor login ui will displayed by the supertokens library.
Removed setup requirements which were solely for login system functioning.
- https://discord.com/channels/603466164219281420/644849840475602944/873090349277532171
- Make it more concise.
> Update appinfo.mdx for the sessions only recipe

- v2/community/database-setup/mysql.mdx
- v2/community/database-setup/postgresql.mdx
- v2/emailpassword/quick-setup/database-setup/mysql.mdx
- v2/emailpassword/quick-setup/database-setup/postgresql.mdx
- v2/session/quick-setup/database-setup/mysql.mdx
- v2/session/quick-setup/database-setup/postgresql.mdx
- v2/thirdparty/quick-setup/database-setup/mysql.mdx
- v2/thirdparty/quick-setup/database-setup/postgresql.mdx
- v2/thirdpartyemailpassword/quick-setup/database-setup/mysql.mdx
- v2/thirdpartyemailpassword/quick-setup/database-setup/postgresql.mdx
- Made `CHAR(36)` to `VARCHAR(128) for UserId type in non auth recipes.
- https://github.com/supertokens/supertokens-core/issues/258
> changes to sql type of userId for email verification

- v2/emailpassword/quick-setup/frontend.mdx
- v2/session/quick-setup/frontend.mdx
- v2/thirdparty/quick-setup/frontend.mdx
- v2/thirdpartyemailpassword/quick-setup/frontend.mdx
Added clarity on the usage of the axios interceptors in the description.
Current description gives the wrong impression that it should always be set on the axios import but this doesn't work if we're not directly using the imported static axios object such as when [creating an axios instance](https://github.com/axios/axios#creating-an-instance) and using that instance throughout the codebase instead of importing axios everywhere.
> docs: clarity on axios interceptors

- v2/community/database-setup/mysql.mdx
- v2/community/database-setup/postgresql.mdx
- v2/emailpassword/quick-setup/database-setup/mysql.mdx
- v2/emailpassword/quick-setup/database-setup/postgresql.mdx
- v2/session/quick-setup/database-setup/mysql.mdx
- v2/session/quick-setup/database-setup/postgresql.mdx
- v2/thirdparty/quick-setup/database-setup/mysql.mdx
- v2/thirdparty/quick-setup/database-setup/postgresql.mdx
- v2/thirdpartyemailpassword/quick-setup/database-setup/mysql.mdx
- v2/thirdpartyemailpassword/quick-setup/database-setup/postgresql.mdx
Adds the `CREATE TABLE` queries for jwt_signing_keys for both MySQL and PostgresSQL to all recipe database setup docs (under the create tables section)
- https://github.com/supertokens/for-zenhub/issues/16
> Add create query for jwt_signing_keys table for MySQL and PostgresSQL

- v2/community/database-setup/mysql.mdx
- v2/community/database-setup/postgresql.mdx
- v2/community/migration/away-from-st.mdx
- v2/emailpassword/common-customizations/sessions/jwt-signing-key-rotation.mdx
- v2/emailpassword/quick-setup/database-setup/mysql.mdx
- v2/emailpassword/quick-setup/database-setup/postgresql.mdx
- v2/session/common-customizations/sessions/jwt-signing-key-rotation.mdx
- v2/session/quick-setup/database-setup/mysql.mdx
- v2/session/quick-setup/database-setup/postgresql.mdx
- v2/thirdparty/common-customizations/sessions/jwt-signing-key-rotation.mdx
- v2/thirdparty/quick-setup/database-setup/mysql.mdx
- v2/thirdparty/quick-setup/database-setup/postgresql.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/jwt-signing-key-rotation.mdx
- v2/thirdpartyemailpassword/quick-setup/database-setup/mysql.mdx
- v2/thirdpartyemailpassword/quick-setup/database-setup/postgresql.mdx
Updated docs to reflect changes in supertokens/supertokens-core#307:
- New table
- Access token signing keys are stored elsewhere
- I couldn't find docs about manually updating keys.
- supertokens/supertokens-core#305
> Multiple access token signing keys doc update

- v2/nodejs/jwt/createJWT.mdx
- v2/nodejs/jwt/getJWKS.mdx
- v2/nodejs/jwt/init.mdx
- v2/nodejs/jwt/override/apis.mdx
- v2/nodejs/jwt/override/functions.mdx
- v2/nodejs/sidebars.js
Adds function docs for the JWT recipe to NodeJS SDK reference docs
- https://github.com/supertokens/for-zenhub/issues/16
- https://github.com/supertokens/supertokens-node/pull/181
> Add JWT docs to NodeJS SDK reference

- v2/emailpassword/nestjs/guide.mdx
- v2/session/nestjs/guide.mdx
- v2/thirdparty/nestjs/guide.mdx
- v2/thirdpartyemailpassword/nestjs/guide.mdx
Moved SDK initialization into a service so that that event handlers can use injected services.
- #130
> Moved SDK init into a service in NestJS guide

- v2/thirdparty/quick-setup/backend.mdx
- v2/thirdpartyemailpassword/quick-setup/backend.mdx
Adds missing Apple imports in backend setup docs
- https://github.com/supertokens/docs/issues/5
- none
> adds missing Apple imports

- v2/emailpassword/nextjs/init.mdx
Use `yarn add` instead of `yarn install` for commands.
> Use yarn add instead of install

- v2/src/components/tabs/PythonSyncAsyncSubTabs.tsx
- v2/thirdparty/advanced-customizations/apis-override/disabling.mdx
- v2/thirdparty/nestjs/guide.mdx
- v2/thirdparty/quick-setup/backend.mdx
- v2/thirdparty/serverless/with-aws-lambda/backend-config.mdx
- Thirdparty providers input config corrections
- default value of asyncio/sycnio tab for python sdk is now correctly set
> thirdparty providers config fixes

- v2/emailpassword/nestjs/guide.mdx
- v2/session/nestjs/guide.mdx
- v2/thirdparty/nestjs/guide.mdx
- v2/thirdpartyemailpassword/nestjs/guide.mdx
In case of errors, we are sending responses inside verifySession instead of calling the next function. 
The NestJS guide needed to be updated to handle this correctly as it expected the next call and tried to send the response again and allowed some wrong calls through the guard.
- Problem reported by email.
> Updated nestjs guide to handle responses sent in verifySession

- v2/docusaurus.config.js
- Updates the algolia config to use the new credentials
- tested out changes on local setup to make sure search still works
https://github.com/supertokens/docs/issues/179
- none
> updates algolia configs with new credentials

- v2/emailpassword/quick-setup/backend.mdx
- v2/session/quick-setup/backend.mdx
- v2/thirdparty/quick-setup/backend.mdx
- v2/thirdpartyemailpassword/quick-setup/backend.mdx
`mode` config parameter is now supported for framework `fastapi` in supertokens-python sdk.
> added mode config for fastapi framework

- v2/emailpassword/common-customizations/get-user-info.mdx
- v2/emailpassword/common-customizations/sessions/session-verification-in-api/verify-session.mdx
- v2/emailpassword/common-customizations/verify-session.mdx
- v2/emailpassword/nestjs/guide.mdx
- v2/passwordless/common-customizations/get-user-info.mdx
- v2/passwordless/common-customizations/sessions/session-verification-in-api/verify-session.mdx
- v2/passwordless/common-customizations/verify-session.mdx
- v2/passwordless/nestjs/guide.mdx
- v2/session/common-customizations/sessions/session-verification-in-api/verify-session.mdx
- v2/session/nestjs/guide.mdx
- v2/thirdparty/common-customizations/get-user-info.mdx
- v2/thirdparty/common-customizations/sessions/session-verification-in-api/verify-session.mdx
- v2/thirdparty/common-customizations/verify-session.mdx
- v2/thirdparty/nestjs/guide.mdx
- v2/thirdpartyemailpassword/common-customizations/get-user-info.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/session-verification-in-api/verify-session.mdx
- v2/thirdpartyemailpassword/common-customizations/verify-session.mdx
- v2/thirdpartyemailpassword/nestjs/guide.mdx
Re-using the Guard in verify session and get user info docs.
- supertokens/docs#185
> Reusing Guard from guide in nestjs docs

- v2/contribute/recipe-design/frontend.mdx
Adds details to the contributing docs for the Frontend SDK for designing recipe functions keeping in mind
- Custom API inputs for each function along with a recipe level API hook
- Custom response types from functions to support custom API responses
https://github.com/supertokens/for-zenhub/issues/96
> Update frontend sdk recipe design contributing docs

- v2/emailpassword/quick-setup/backend.mdx
- v2/passwordless/quick-setup/backend.mdx
- v2/session/quick-setup/backend.mdx
- v2/thirdparty/quick-setup/backend.mdx
- v2/thirdpartyemailpassword/quick-setup/backend.mdx
Fix typo. Change `djnago` -> `django`
NA
NA
> Fix typo in name Django

- v2/community/supertokens-core/self-hosted/base-path.mdx
- v2/emailpassword/common-customizations/core/base-path.mdx
- v2/emailpassword/sidebars.js
- v2/passwordless/common-customizations/core/base-path.mdx
- v2/passwordless/sidebars.js
- v2/thirdparty/common-customizations/core/base-path.mdx
- v2/thirdparty/sidebars.js
- v2/thirdpartyemailpassword/common-customizations/core/base-path.mdx
- v2/thirdpartyemailpassword/sidebars.js
Adds docs for how to setup a base path for the core
- https://github.com/supertokens/supertokens-node/issues/252
> adds docs for core base path

- v2/emailpassword/common-customizations/translations.mdx
- v2/emailpassword/sidebars.js
- v2/passwordless/common-customizations/translations.mdx
- v2/passwordless/sidebars.js
- v2/thirdparty/common-customizations/translations.mdx
- v2/thirdparty/sidebars.js
- v2/thirdpartyemailpassword/common-customizations/translations.mdx
- v2/thirdpartyemailpassword/sidebars.js
Adding docs about adding custom translations
- https://github.com/supertokens/supertokens-auth-react/issues/233
> docs: add docs for custom translations

- v2/community/introduction.mdx
- v2/emailpassword/introduction.mdx
- v2/passwordless/introduction.mdx
- v2/session/introduction.mdx
- v2/thirdparty/introduction.mdx
- v2/thirdpartyemailpassword/introduction.mdx
- Removed the bullet point from these files
1.  v2/community/introduction.mdx
2. v2/emailpassword/introduction.mdx
3. v2/passwordless/introduction.mdx
4. v2/session/introduction.mdx
5. v2/thirdparty/introduction.mdx
6. v2/thirdpartyemailpassword/introduction.mdx
- https://github.com/supertokens/docs/issues/227
> 📄 Docs: Remove the bullet points from the features list in the "About this recipe" section.

- v2/community/database-setup/postgresql.mdx
- v2/emailpassword/quick-setup/database-setup/postgresql.mdx
- v2/passwordless/quick-setup/database-setup/postgresql.mdx
- v2/session/quick-setup/database-setup/postgresql.mdx
- v2/thirdparty/quick-setup/database-setup/postgresql.mdx
- v2/thirdpartyemailpassword/quick-setup/database-setup/postgresql.mdx
Updated Postgres docs with the new index on device_id_hash for codes
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/31
> updated postgres docs with new index on device_id_hash for codes

- v2/src/components/compatibility/index.tsx
- #247 
- The Backend API sends sorted compatibility data.
- As a result, we do not need the sorting logic on frontend.
- So we are removing the sorting logic from the frontend.
- The method `sortCompatibilityResponse` is called on the response from the backend which handles the sorting. The method itself and the call to that method on the response is removed.
- The method `sortDoubleDecimalCompatibilityResponse` is used inside `sortCompatibilityResponse` to handle sorting. It is not used anywhere else. This method is also removed.
- The `sortDoubleDecimalNumbers` method is not used anywhere in the component and it does not have any useful logic, so that method is removed too.
- Note: The form doesn't work on the preview because of CORS error. Here's the [demo …
> Remove sorting logic from frontend for compatibility table

- v2/change_me/introduction.mdx
- v2/src/css/custom.css
- Updated styles for admonition as per the 3rd admonition design in this [Zeplin design](https://app.zeplin.io/project/5aaa0de98d835c7b25637f2e/screen/6170fdc5160556a2de9430df)
- Epic: https://github.com/supertokens/main-website/issues/576
- #260
> Docs redesign: updated styles for admonitions

- v2/src/components/appInfoForm/index.tsx
- v2/src/components/appInfoForm/style.css
- Removes the preview snippet that shows the currently saved values for the fields in AppInfoForm.
- #258 - https://github.com/supertokens/docs/issues/258#issuecomment-1084330307
> Remove current entered values preview from appInfoForm

- v2/src/components/appInfoForm/index.tsx
- #263 
- #254 
- fixed #263 - Convert the domain to lower case using `String.toLowerCase()` method when calling the normalization class `NormalisedURLDomain`.
- #254: Updated the error message we show when using Netlify Functions and the apiBasePath is not prefixed by `/.netlify/functions/` or does not contain any path after that.
- Updated message: **"apiBasePath must be prefixed with \`/.netlify/functions\`, for example to use \`/auth\` set the apiBasePath to \`/.netlify/functions/auth\`"**
> Bug fix for AppInfoForm and updated error message for invalid apiBasePath when using Netlify functions

- v2/src/components/snippetConfigForm/index.tsx
- The question component in passwordless docs uses `replaceAll` method in strings, which is not available in Safari 12.
- We replace this `replaceAll(stringWhichIsReplaced, stringThatReplaces)` by `.split(stringWhichIsReplaced).join(stringThatReplaces)`. This method is used in the `AppInfoForm` and works on Safari 12.
- [iPad Air iOS v12.4](https://drive.google.com/file/d/1xSkouLU4Vfe25JORA0mZgDKIYX1cb-JD/view?usp=sharing)
- #267 
> Remove usage of replaceAll from question component in passwordless docs

- v2/emailpassword/quick-setup/backend.mdx
- v2/emailpassword/quick-setup/frontend.mdx
- v2/passwordless/quick-setup/backend.mdx
- v2/passwordless/quick-setup/frontend.mdx
- v2/src/components/tabs/FrontendSDKTabs.tsx
- v2/thirdparty/quick-setup/backend.mdx
- v2/thirdparty/quick-setup/frontend.mdx
- v2/thirdpartyemailpassword/quick-setup/backend.mdx
- v2/thirdpartyemailpassword/quick-setup/frontend.mdx
- v2/thirdpartypasswordless/quick-setup/backend.mdx
- v2/thirdpartypasswordless/quick-setup/frontend.mdx
- Changes the admonition for Plain Javascript to better explain how to use the SDK by building your own UI
- Adds an admonition to the frontend and backend quick setup guides for all recipes to explain that SuperTokens.init uses both the recipe itself and the session recipe and that the user can do the same thing to use multiple recipes
- None
> Add additional information about using plain javascript and add an admonition for using multiple recipes

- v2/emailpassword/quick-setup/frontend.mdx
- v2/passwordless/quick-setup/frontend.mdx
- v2/src/components/tabs/FrontendSDKTabs.tsx
- v2/thirdparty/quick-setup/frontend.mdx
- v2/thirdpartyemailpassword/quick-setup/frontend.mdx
- v2/thirdpartypasswordless/quick-setup/frontend.mdx
- Changes the content of the admonition for react-native in the frontend quick setup guide and snippets that apply to pre-built UI
- None
> Modify react native tab for quick setup and UI operations

- v2/emailpassword/quick-setup/backend.mdx
- v2/passwordless/quick-setup/backend.mdx
- v2/session/quick-setup/backend.mdx
- v2/thirdparty/quick-setup/backend.mdx
- v2/thirdpartyemailpassword/quick-setup/backend.mdx
- v2/thirdpartypasswordless/quick-setup/backend.mdx
code snippet fix for flask. This is required since if this is not there, then OPTIONS requests for the APIs exposed by the supertokens' Middleware will return a 404
> code snippet fix for flask

- v2/src/components/appInfoForm/formItem.tsx
- v2/src/components/appInfoForm/index.tsx
- v2/src/components/question/index.tsx
- v2/src/components/snippetConfigForm/formQuestion.tsx
- v2/src/theme/DocSidebar/index.js
- Adds `alt` tags to the images displayed in the left sidebar.
- Adds `alt` tag to the "Double check" image used in AppInfoForm and Question components 'saved' state.
- Adds `alt` tag to the "?" icon next to questions in the AppInfoForm
- #299 
- #301 
> add alt tag to icons in sidebar menu

- v2/src/components/appInfoForm/index.tsx
- If we do not add any domains, and enter same values for `apiBasePath` and `websiteBasePath`, the `appInfoForm` shows 3 errors, 2 on the empty domains and 1 on `apiBasePath` saying that the paths cannot be equal.
- If the domains are empty, the paths should not be validated for the case where if the domains are equal, the paths cannot be equal or be prefixed by each other.
- #275 
No TODOs remaining
> In appInfoForm, validate the equal paths case only if the domains exist

- v2/emailpassword/migration/from-auth0/account-migration/modifications-to-login.mdx
- v2/passwordless/migration/from-auth0/account-migration/modifications-to-login.mdx
- v2/thirdparty/migration/from-auth0/account-migration/modifications-to-login.mdx
- v2/thirdpartyemailpassword/migration/from-auth0/account-migration/modifications-to-login.mdx
- v2/thirdpartypasswordless/migration/from-auth0/account-migration/modifications-to-login.mdx
Added alt text to account migration images on following pages
- https://test.supertokens.com/docs/emailpassword/migration/from-auth0/account-migration/modifications-to-login
- https://test.supertokens.com/docs/passwordless/migration/from-auth0/account-migration/modifications-to-login
- https://test.supertokens.com/thirdparty/migration/from-auth0/account-migration/modifications-to-login
- https://test.supertokens.com/docs/thirdpartyemailpassword/migration/from-auth0/account-migration/modifications-to-login ( `Email Password Account Migration` and `Social Account Migration` tabs )
- https://test.supertokens.com/docs/thirdpartypasswordless/migration/from-auth0/account-migration/modifications-to-login ( `Passwordless Account Migration` and `Social Account Migration` tabs )
Added alt text to …
> Added alt text to account migration and auth0 database images

- v2/community/architecture.mdx
- v2/emailpassword/architecture.mdx
- v2/passwordless/architecture.mdx
- v2/session/architecture.mdx
- v2/thirdparty/architecture.mdx
- v2/thirdpartyemailpassword/architecture.mdx
- v2/thirdpartypasswordless/architecture.mdx
- Adds alt text to flowchart images in the architecture pages
Note: The architecture files in recipes are copied from the `v2/community/architecture.mdx` file.
- #305 
> Add alt text to architecture page flowcharts

- v2/emailpassword/common-customizations/styling/themes.mdx
- v2/thirdparty/common-customizations/styling/themes.mdx
- v2/thirdpartyemailpassword/common-customizations/styling/themes.mdx
Adds alt text to the images of themes in the following pages
- https://test.supertokens.com/docs/emailpassword/common-customizations/styling/themes
- https://test.supertokens.com/docs/thirdparty/common-customizations/styling/themes
- https://test.supertokens.com/docs/thirdpartyemailpassword/common-customizations/styling/themes
- #305 
No TODOs remaining
> Add alt text to images of themes for thirdparty, emailpassword and thirdpartyemailpassword

- v2/emailpassword/common-customizations/styling/changing-style.mdx
- v2/passwordless/common-customizations/styling/changing-style.mdx
- v2/src/components/appInfoForm/index.tsx
- v2/thirdparty/common-customizations/sign-in-and-up/custom-providers.mdx
- v2/thirdparty/common-customizations/styling/changing-style.mdx
- v2/thirdpartyemailpassword/common-customizations/signup-form/custom-providers.mdx
- v2/thirdpartyemailpassword/common-customizations/styling/changing-style.mdx
- v2/thirdpartypasswordless/common-customizations/signup-form/custom-providers.mdx
- v2/thirdpartypasswordless/common-customizations/styling/changing-style.mdx
- The rehype plugin added in the PR #319 adds `rel="nofollow noopener noreferrer"` to external links written in markdown syntax. This PR updates the links in docs that are not written using the markdown syntax to use the markdown syntax so that the attributes are added to them.
- We also add `rel="nofollow noopener noreferrer` to the NextJS API routes link in the `AppInfoForm`.
- #317
> Updated external links that were not getting fixed by the plugin

- v2/docusaurus.config.js
- v2/src/plugins/addNofollowToExternalLinks.js
- Created a rehype plugin that modifies the nodes of docs that are links.
- It checks if the link is an external link and adds `rel="nofollow noopener noreferrer"` ( I included `noopener noreferrer` because that was already being added before this plugin. )
- The reason why I added a rehype plugin instead of a remark plugin, is that after the remark plugins make changes to nodes, docusaurus was adding `_target="blank" rel="noopener noreferrer"` to the links and discarding the `nofollow` added by the remark plugin.
- #317
> Created plugin to add `rel="nofollow"` to external links in docs

- v2/thirdparty/nestjs/guide.mdx
- v2/thirdparty/nextjs/init.mdx
- v2/thirdparty/quick-setup/backend.mdx
- v2/thirdparty/serverless/with-aws-lambda/backend-config.mdx
- v2/thirdparty/serverless/with-netlify/backend-config.mdx
- v2/thirdpartyemailpassword/nestjs/guide.mdx
- v2/thirdpartyemailpassword/nextjs/init.mdx
- v2/thirdpartyemailpassword/quick-setup/backend.mdx
- v2/thirdpartyemailpassword/serverless/with-aws-lambda/backend-config.mdx
- v2/thirdpartyemailpassword/serverless/with-netlify/backend-config.mdx
- v2/thirdpartypasswordless/quick-setup/backend.mdx
- v2/thirdpartypasswordless/serverless/with-aws-lambda/backend-config.mdx
- v2/thirdpartypasswordless/serverless/with-netlify/backend-config.mdx
I was reading your docs and saw a small spelling error for OAuth tokens that you so kindly provide. So I went ahead and fixed it with ripgrep and sed :smile: 
For full transparency I ran this:
`rg testsing --files-with-matches | xargs sed -i 's/testsing/testing/'`
Let me know if there is something that I missed or if I am not following the correct protocol :smile_cat: 
This is a great tool :star: !
None, a simple spell fix in multiple files
~~- [ ] Algolia search needs to be updated? (If there is a new sub docs project, then yes)~~
~~- [ ] Sitemap needs to be updated? (If there is a new sub docs project, then yes)~~
~~- [ ] Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)~~
~~- [ ] Changes required to the demo apps corresponding to the docs?~~
> Fix testing spelling

- v2/thirdparty/common-customizations/account-linking.mdx
- v2/thirdpartyemailpassword/common-customizations/account-linking.mdx
- v2/thirdpartypasswordless/common-customizations/account-linking.mdx
- Update `How to enable this feature?` section in `/common-customizations/account-linking` to explain that the feature is still a work in progress and SuperTokens does not support this yet
- ...
> refactor: Update section on how to enable account linking to say its in progress

- v2/emailpassword/common-customizations/signin-form/field-validators.mdx
- v2/thirdparty/advanced-customizations/apis-override/usage.mdx
- v2/thirdpartyemailpassword/common-customizations/signin-form/field-validators.mdx
- Fixes the issue of pages not having h1 tags in `emailpassword`, `thirdpartyemailpassword` and `thirdparty` recipes
- https://github.com/supertokens/for-zenhub/issues/131
> Fix issue of no h1 tags in emailpassword, thirdpartyemailpassword, thirdparty

- nodejs/docs/thirdparty/providers/apple.md
- nodejs/docs/thirdparty/providers/facebook.md
- nodejs/docs/thirdparty/providers/github.md
- nodejs/docs/thirdparty/providers/google.md
- nodejs/website/versioned_docs/version-1.0.X/api-reference/create-new-session.md
- nodejs/website/versioned_docs/version-1.0.X/api-reference/get-session.md
- nodejs/website/versioned_docs/version-1.0.X/api-reference/refresh-session.md
- nodejs/website/versioned_docs/version-2.0.X/api-reference/middleware/supertokens-error-handler.md
- nodejs/website/versioned_docs/version-2.3.X/api-reference/middleware/supertokens-error-handler.md
- nodejs/website/versioned_docs/version-4.1.X/thirdparty/providers/apple.md
- nodejs/website/versioned_docs/version-4.1.X/thirdparty/providers/facebook.md
- nodejs/website/versioned_docs/version-4.1.X/thirdparty/providers/github.md
- nodejs/website/versioned_docs/version-4.1.X/thirdparty/providers/google.md
Some docs for `nodejs` sdk in v1 have multiple h1 tags.
This PR updates those docs to only have 1 h1 tag.
- https://github.com/supertokens/for-zenhub/issues/135
> Fix issue of multiple h1 in nodejs docs v1

- CONTRIBUTING.md
- v2/src/components/tabs/FrontendSDKTabs.tsx
You can now add multiple `,` separated tabIds with copy tabs so if the first one doesn't exist, it will keep searching for a match
none
> Copytab enhancements

- v2/emailpassword/common-customizations/sessions/in-iframe.mdx
- v2/emailpassword/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/emailpassword/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/passwordless/common-customizations/sessions/in-iframe.mdx
- v2/passwordless/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/passwordless/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/session/common-customizations/sessions/in-iframe.mdx
- v2/session/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/session/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/src/components/reusableSnippets/sessionConfigDisclaimer.tsx
- v2/thirdparty/common-customizations/sessions/in-iframe.mdx
- v2/thirdparty/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/thirdparty/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/in-iframe.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/in-iframe.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/share-session-across-sub-domains.mdx
Adds a disclaimer message in angular tabs where both `supertokens-auth-react` and `supertokens-web-js` need to be changed
- https://github.com/supertokens/docs/issues/369
- none
> adds session config  disclaimer for angular tabs

- v2/emailpassword/advanced-customizations/apis-override/usage.mdx
- v2/emailpassword/advanced-customizations/backend-functions-override/usage.mdx
- v2/passwordless/advanced-customizations/apis-override/usage.mdx
- v2/passwordless/advanced-customizations/backend-functions-override/usage.mdx
- v2/session/advanced-customizations/apis-override/usage.mdx
- v2/session/common-customizations/sessions/new-session.mdx
- v2/thirdparty/advanced-customizations/apis-override/usage.mdx
- v2/thirdparty/advanced-customizations/backend-functions-override/usage.mdx
- v2/thirdpartyemailpassword/advanced-customizations/apis-override/usage.mdx
- v2/thirdpartyemailpassword/advanced-customizations/backend-functions-override/usage.mdx
- v2/thirdpartypasswordless/advanced-customizations/apis-override/usage.mdx
- v2/thirdpartypasswordless/advanced-customizations/backend-functions-override/usage.mdx
- Modifies the links for golang reference docs to remove the package version (this makes it point to the latest version by default) to solve 404s. 
- Fixes some links for golang that gave a 400
- ...
None
> Fix reference docs links for supertokens-golang

- v2/emailpassword/common-customizations/sessions/update-jwt-payload.mdx
- v2/emailpassword/common-customizations/sessions/update-session-data.mdx
- v2/emailpassword/common-customizations/sessions/with-jwt/read-claims.mdx
- v2/emailpassword/common-customizations/sessions/with-jwt/read-jwt.mdx
- v2/emailpassword/common-customizations/sessions/with-jwt/update-jwt.mdx
- v2/passwordless/common-customizations/sessions/update-jwt-payload.mdx
- v2/passwordless/common-customizations/sessions/update-session-data.mdx
- v2/passwordless/common-customizations/sessions/with-jwt/read-claims.mdx
- v2/passwordless/common-customizations/sessions/with-jwt/read-jwt.mdx
- v2/passwordless/common-customizations/sessions/with-jwt/update-jwt.mdx
- v2/session/common-customizations/sessions/update-jwt-payload.mdx
- v2/session/common-customizations/sessions/update-session-data.mdx
- v2/session/common-customizations/sessions/with-jwt/read-claims.mdx
- v2/session/common-customizations/sessions/with-jwt/read-jwt.mdx
- v2/session/common-customizations/sessions/with-jwt/update-jwt.mdx
- v2/thirdparty/common-customizations/sessions/update-jwt-payload.mdx
- v2/thirdparty/common-customizations/sessions/update-session-data.mdx
- v2/thirdparty/common-customizations/sessions/with-jwt/read-claims.mdx
- v2/thirdparty/common-customizations/sessions/with-jwt/read-jwt.mdx
- v2/thirdparty/common-customizations/sessions/with-jwt/update-jwt.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/update-jwt-payload.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/update-session-data.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/with-jwt/read-claims.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/with-jwt/read-jwt.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/with-jwt/update-jwt.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/update-jwt-payload.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/update-session-data.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/with-jwt/read-claims.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/with-jwt/read-jwt.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/with-jwt/update-jwt.mdx
- Fixes variable names to be more accurate to the method calls for Python code snippets where `get_session_information` is used
- Makes variable names more consistent across different docs pages
- ...
> chore: Fix variable names for session information for python docs

- v2/emailpassword/common-customizations/sessions/with-jwt/get-public-key.mdx
- v2/passwordless/common-customizations/sessions/with-jwt/get-public-key.mdx
- v2/session/common-customizations/sessions/with-jwt/get-public-key.mdx
- v2/thirdparty/common-customizations/sessions/with-jwt/get-public-key.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/with-jwt/get-public-key.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/with-jwt/get-public-key.mdx
- Explains that the API key needs to be set when calling the JWKS endpoint
> Add a note about API keys when calling the JWKS endpoint

- v2/src/css/custom.css
- Show the Drift chat button above v2 docs menu button so that it does not overlap
- #304 
- [Drive video link](https://drive.google.com/file/d/1cPYd0Qg1Zi9CAMpxC0-dYoYccUVhPxs5/view?usp=sharing)
> Move Drift chat icon above the menu button in v2 docs tablet view

- v2/emailpassword/nestjs/guide.mdx
- v2/passwordless/nestjs/guide.mdx
- v2/session/nestjs/guide.mdx
- v2/thirdparty/nestjs/guide.mdx
- v2/thirdpartyemailpassword/nestjs/guide.mdx
- v2/thirdpartypasswordless/nestjs/guide.mdx
In nestJS guide, give code snippet for "The nest CLI will add this service to the normal module providers, which you should move to the `providers` prop of the module returned in `forRoot`." step.
-
> Add code code for moving nestjs service

- v2/src/components/appInfoForm/normalisedURLDomain.ts
- When the user inputs `localhost:443`, AppInfoForm now normalises the domain to `https://localhost` instead of `http://localhost`
- #278 
No TODOs remaining
> Fix appInfoForm error when default ports are selected for domain

- v2/src/components/tabs/FrontendSDKTabs.tsx
Changes the copy for the admonition in the default Plain Javascript tab to link to the vue JS example app for `supertokens-web-js`
> Update copy for default plain js tab

- v2/emailpassword/nextjs/session-verification/in-api.mdx
- v2/emailpassword/nextjs/setting-up-backend.mdx
- v2/passwordless/nextjs/session-verification/in-api.mdx
- v2/passwordless/nextjs/setting-up-backend.mdx
- v2/src/components/appInfoForm/index.tsx
- v2/src/components/appInfoForm/style.css
- v2/src/css/custom.css
- v2/thirdparty/nextjs/session-verification/in-api.mdx
- v2/thirdparty/nextjs/setting-up-backend.mdx
- v2/thirdpartyemailpassword/nextjs/session-verification/in-api.mdx
- v2/thirdpartyemailpassword/nextjs/setting-up-backend.mdx
- v2/thirdpartypasswordless/nextjs/session-verification/in-api.mdx
- v2/thirdpartypasswordless/nextjs/setting-up-backend.mdx
- utilizing DOM attributes, Mutation Observer & InterractionObserver
- when user click the resubmit, it will find the first `appInfoForm`, and then update `display-form` DOM attribute
- Mutation Observer that listen to the attribute changes
- refactor render method and break it into 2 methods
- workaround on details element
- https://github.com/supertokens/main-website/issues/879
- #408 
NA
> Fix: The new Single app info form branch

- v2/src/theme/NavbarItem/RecipeLabelItem.js
only run `isMobile` on browser and not during SSG
- #450 
NA
> fix: avoid run isMobile on SSG

- v2/src/plugins/codeTypeChecking/index.js
- v2/src/plugins/copyDocsAndCodeTypeChecking.js
- Changes code type checking to generate swift code files only if swift is specifically enabled when running the start script
> Fix code type checking for swift

- v2/community/supertokens-core/self-hosted/with-docker.mdx
- v2/emailpassword/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/emailpassword/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/passwordless/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/passwordless/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/session/quick-setup/core/self-hosted-with-docker.mdx
- v2/src/components/api/plugin/dependency/cores.ts
- v2/src/components/dockerVersionProvider/index.tsx
- v2/thirdparty/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/thirdparty/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/thirdpartyemailpassword/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/thirdpartypasswordless/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/core/self-hosted-with-docker.mdx
When adding snippets for docker (run or compose files) we now use the DockerVersionProvider component to fetch the latest core version to use
-
> chore: Add docker version provider component to add version to docker snippets for core

- v2/contribute/decisions/session/0007-session-verification-should-allow-fallback.mdx
- v2/contribute/decisions/session/0008-active-session-cant-change-auth-modes.mdx
- v2/contribute/decisions/session/0020-validating-token-transfer-method-during-verification.mdx
Re-add respecting getTokenTransferMethod into verify and refreshSession
-
> Re-add respecting getTokenTransferMethod into verify and refreshSession

- v2/contribute/decisions/session/0008-active-session-cant-change-auth-modes.mdx
- v2/contribute/decisions/session/0020-validating-token-transfer-method-during-verification.mdx
- v2/contribute/decisions/session/0021-clearing-session-during-create.mdx
- v2/contribute/sidebars.js
Document why `createNewSession` clears tokens
- minor cleanup in other ADRs
- fixed mistake in refresh behaviour table
-
> ADR: document why createNewSession clears tokens

- v2/emailpassword/custom-ui/init/dashboard.mdx
- v2/emailpassword/pre-built-ui/setup/dashboard.mdx
- v2/passwordless/custom-ui/init/dashboard.mdx
- v2/passwordless/pre-built-ui/setup/dashboard.mdx
- v2/thirdparty/custom-ui/init/dashboard.mdx
- v2/thirdparty/pre-built-ui/setup/dashboard.mdx
- v2/thirdpartyemailpassword/custom-ui/init/dashboard.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/dashboard.mdx
- v2/thirdpartypasswordless/custom-ui/init/dashboard.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/dashboard.mdx
- Because the dashboard is served by the backend, adding any CSP headers also affects the dashboard frontend. This PR adds the headers needed to make the dashboard work properly and without any errors
-
> chore: Add docs for adding content security policy headers for the dashboard feature

- v2/community/architecture.mdx
- v2/emailpassword/architecture.mdx
- v2/passwordless/architecture.mdx
- v2/phonepassword/architecture.mdx
- v2/session/architecture.mdx
- v2/thirdparty/architecture.mdx
- v2/thirdpartyemailpassword/architecture.mdx
- v2/thirdpartypasswordless/architecture.mdx
- The how it works video would not allow playing in full screen mode (the only way to do that would be to open the video on youtube). This PR fixes the embed to explicitly make allowfullscreen true on the embed player
-
> fix: Add fullscreen support to how it works video

- v2/src/theme/TOC/index.js
- In tablet portrait mode, the tick mark next to the sdk name would sometimes render outside of the button. This PR fixes this behaviour
-
> fix: Fix issue with custom/prebuilt ui selector in tablet portrait mode

- v2/contribute/decisions/accountlinking/0004-separate-api-post-login-for-account-linking.mdx
- v2/contribute/sidebars.js
- ADR: why we have separate API for post login account linking
> why we have separate API for post login account linking

- v2/emailpassword/nextjs/setting-up-frontend.mdx
- v2/passwordless/nextjs/setting-up-frontend.mdx
- v2/thirdparty/nextjs/setting-up-frontend.mdx
- v2/thirdpartyemailpassword/nextjs/setting-up-frontend.mdx
- v2/thirdpartypasswordless/nextjs/setting-up-frontend.mdx
In thirdpartyemailpassword section for setting up the front end, the example code link redirecting to the nextjs example with supertokens was wrong.
https://github.com/supertokens/docs/issues/551
> fix: third party auth setup link for nextjs

- v2/passwordless/sms-delivery/about.mdx
- v2/thirdpartypasswordless/sms-delivery/about.mdx
Fixes the title of the custom SMS sending section of the passwordless docs to not say "email"
-
> fix: Fix title for custom sms sending section

- v2/contribute/decisions/reactsdk/0001-move-override-config-to-separate-component-prop.mdx
- v2/contribute/sidebars.js
Add discussion on moving components override config out of init call
- https://github.com/supertokens/supertokens-auth-react/issues/616
> adr: moving override config to separate component's prop

- v2/contribute/decisions/multitenancy/0011-using-provider-input-instead-of-provider-init.mdx
- v2/emailpassword/advanced-customizations/react-component-override/usage.mdx
- v2/emailpassword/email-delivery/smtp/configure-smtp.mdx
- v2/emailpassword/supabase-intergration/backend-signup-override.mdx
- v2/mfa/pre-built-ui/showing-login-ui.mdx
- v2/passwordless/advanced-customizations/react-component-override/usage.mdx
- v2/passwordless/supabase-intergration/backend-signup-override.mdx
- v2/src/plugins/codeTypeChecking/jsEnv/package.json
- v2/thirdparty/advanced-customizations/react-component-override/usage.mdx
- v2/thirdpartyemailpassword/advanced-customizations/react-component-override/usage.mdx
- v2/thirdpartypasswordless/advanced-customizations/react-component-override/usage.mdx
- v2/thirdpartypasswordless/supabase-intergration/backend-signup-override.mdx
Moving components override config to a separate component
- https://github.com/supertokens/supertokens-auth-react/issues/616
-
> docs: move components override config for auth react

- v2/contribute/decisions/session/0022-ssr-jwt-use-case.mdx
- v2/contribute/decisions/session/0024-access-tokenstandard-jwt-claims.mdx
- v2/contribute/decisions/session/0030-get-session-from-string.mdx
- Added `kid` header param into ADR about new jwt structure
- Added note to mention `exposeAccessTokenToFrontendInCookieBasedAuth` in `getAccessToken` docs
-
> Small updates to jwt rework related ADRs

- v2/community/supertokens-core/self-hosted/with-docker.mdx
- v2/emailpassword/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/emailpassword/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/passwordless/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/passwordless/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/session/quick-setup/core/self-hosted-with-docker.mdx
- v2/thirdparty/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/thirdparty/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/thirdpartyemailpassword/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/thirdpartypasswordless/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/core/self-hosted-with-docker.mdx
Instead of:
```docker
supertokens:
image: registry.supertokens.io/supertokens/supertokens-postgresql:4.3
depends_on:
- db
```
It should be:
```docker
supertokens:
image: registry.supertokens.io/supertokens/supertokens-postgresql:4.3
depends_on:
db:
condition: service_healthy
```
- [Docker compose file should use health check. #557 
](https://github.com/supertokens/supertokens-core/issues/557)
> fix: Added service up check command in docker compose files

- v2/contribute/decisions/session/0015-jwt-compatibility.mdx
- v2/contribute/decisions/session/0024-access-tokenstandard-jwt-claims.mdx
- v2/contribute/decisions/session/0031-internal-prop-handling-in-flat-access-tokens.mdx
- v2/contribute/sidebars.js
Adding ADR about handling front-token after flattening the access token
-
> Adding ADR about handling front-token after flattening the access token

- v2/contribute/decisions/reactsdk/0002-split-recipe-route-handlers-into-separate-comps.mdx
- v2/contribute/sidebars.js
Add adr for splitting recipe routes from recipe init:
We want to enable apps to initialize supertokens-auth-react without bundling react. This is useful for example in angular apps, where we should be able to use a single init call in the main route (and use auth-react throughout the app), while only bundling react to the module handling auth.
-
> adr: add adr for splitting recipe routes from recipe init

- v2/emailpassword/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/emailpassword/common-customizations/sessions/token-transfer-method.mdx
- v2/emailpassword/custom-ui/handling-session-tokens.mdx
- v2/passwordless/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/passwordless/common-customizations/sessions/token-transfer-method.mdx
- v2/passwordless/custom-ui/handling-session-tokens.mdx
- v2/session/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/session/common-customizations/sessions/token-transfer-method.mdx
- v2/thirdparty/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/thirdparty/common-customizations/sessions/token-transfer-method.mdx
- v2/thirdparty/custom-ui/handling-session-tokens.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/token-transfer-method.mdx
- v2/thirdpartyemailpassword/custom-ui/handling-session-tokens.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/token-transfer-method.mdx
- v2/thirdpartypasswordless/custom-ui/handling-session-tokens.mdx
Adds snippets for header based auth for React Native, Android and iOS
-
> chore: Add snippets for mobile SDKs for header based auth

- v2/community/supertokens-core/self-hosted/with-docker.mdx
- v2/emailpassword/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/emailpassword/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/passwordless/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/passwordless/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/session/quick-setup/core/self-hosted-with-docker.mdx
- v2/thirdparty/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/thirdparty/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/thirdpartyemailpassword/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/core/self-hosted-with-docker.mdx
- v2/thirdpartypasswordless/custom-ui/init/core/self-hosted-with-docker.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/core/self-hosted-with-docker.mdx
This change adds a note to avoid using underscores as part of the db service name in the `docker-compose` config for Postgres.  If the db service name includes an underscore e.g. `supertokens_db`, Supertokens will fail to connect to the db server using what appears to be a correct `POSTGRESQL_CONNECTION_URI` (e.g. `"postgresql://supertokens_user:somePassword@supertokens_db:5432/supertokens"`) - full discussion with @rishabhpoddar on Discord [here](https://discord.com/channels/603466164219281420/1069771923938091048).  It's not clear from the error log that the underscores are the problem (it just says it couldn't connect), but I believe it can be traced back to the usage of `java.net.URI.create()` [here](https://github.com/supertokens/supertokens-postgresql-plugin/blob/535a5ba046d4f6b5d0cbe …
> Adds note on avoiding underscores in service name

- v2/emailpassword/common-customizations/sessions/change-session-timeout.mdx
- v2/passwordless/common-customizations/sessions/change-session-timeout.mdx
- v2/session/common-customizations/sessions/change-session-timeout.mdx
- v2/thirdparty/common-customizations/sessions/change-session-timeout.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/change-session-timeout.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/change-session-timeout.mdx
add caution about setting access token expiry over 400 days to 
- https://github.com/supertokens/supertokens-node/issues/492
> add caution about setting access token expiry over 400 days

- v2/session/quick-setup/handling-session-tokens.mdx
- v2/session/sidebars.js
- Adds handling session tokens to session recipe to match the structure of other recipes and to explain the need for interceptors in react native
> chore: Add handling session tokens docs to session recipe

- v2/emailpassword/pre-built-ui/setup/frontend.mdx
- v2/passwordless/pre-built-ui/setup/frontend.mdx
- v2/src/components/tabs/FrontendPreBuiltUITabs.tsx
- v2/thirdparty/pre-built-ui/setup/frontend.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/frontend.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/frontend.mdx
- The new tab explains that we dont provide pre built UI for mobile and links to custom UI quick setup
-
> chore: Add mobile tab for frontend pre built ui quick setup

- v2/emailpassword/custom-ui/init/dashboard.mdx
- v2/emailpassword/pre-built-ui/setup/dashboard.mdx
- v2/passwordless/custom-ui/init/dashboard.mdx
- v2/passwordless/pre-built-ui/setup/dashboard.mdx
- v2/src/plugins/codeTypeChecking/goEnv/go.mod
- v2/src/plugins/codeTypeChecking/goEnv/go.sum
- v2/thirdparty/custom-ui/init/dashboard.mdx
- v2/thirdparty/pre-built-ui/setup/dashboard.mdx
- v2/thirdpartyemailpassword/custom-ui/init/dashboard.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/dashboard.mdx
- v2/thirdpartypasswordless/custom-ui/init/dashboard.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/dashboard.mdx
- v2/userdashboard/about.mdx
> chore: Update golang snippets and env dependency

- v2/src/theme/NavbarItem/index.js
- Fixes the url for the github navbar link on the guides page
-
> fix: Fix guides page github link in the header

- v2/emailpassword/advanced-customizations/react-component-override/usage.mdx
- v2/passwordless/advanced-customizations/react-component-override/usage.mdx
- v2/src/plugins/codeTypeChecking/jsEnv/package.json
- v2/thirdparty/advanced-customizations/react-component-override/usage.mdx
- v2/thirdpartyemailpassword/advanced-customizations/react-component-override/usage.mdx
- v2/thirdpartypasswordless/advanced-customizations/react-component-override/usage.mdx
Adds component override snippets for without react-router-dom usage
> fix: components override guide

- v2/src/css/custom.css
- Adds some space to the right of the icon to not make it touch the edge of its parent container when the recipe text is long (third party email password for example)
-
> Fix styling of recipe selected icon in the recipe selectopn dropdown

- v2/thirdpartyemailpassword/common-customizations/sessions/with-websocket.mdx
> fix: Typo in websocket documentation

- v2/src/plugins/codeTypeChecking/iosenv/Podfile
- v2/src/plugins/codeTypeChecking/iosenv/Podfile.lock
- v2/src/plugins/codeTypeChecking/iosenv/Pods/Manifest.lock
- v2/src/plugins/codeTypeChecking/iosenv/Pods/Pods.xcodeproj/project.pbxproj
- v2/src/plugins/codeTypeChecking/iosenv/Pods/SuperTokensIOS/SuperTokensIOS/Classes/FrontToken.swift
- v2/src/plugins/codeTypeChecking/iosenv/Pods/SuperTokensIOS/SuperTokensIOS/Classes/SuperTokensURLProtocol.swift
- v2/src/plugins/codeTypeChecking/iosenv/Pods/SuperTokensIOS/SuperTokensIOS/Classes/Utils.swift
- v2/src/plugins/codeTypeChecking/iosenv/Pods/SuperTokensIOS/SuperTokensIOS/Classes/Version.swift
- v2/src/plugins/codeTypeChecking/iosenv/Pods/SuperTokensIOS/SuperTokensIOS/Classes/extensions/Dictionary.swift
- v2/src/plugins/codeTypeChecking/iosenv/Pods/Target Support Files/SuperTokensIOS/SuperTokensIOS-Info.plist
- v2/src/plugins/codeTypeChecking/pythonEnv/requirements.txt
> chore: Update code type checking envs

- v2/community/database-setup/mysql.mdx
- v2/community/database-setup/postgresql.mdx
- v2/emailpassword/custom-ui/init/database-setup/mysql.mdx
- v2/emailpassword/custom-ui/init/database-setup/postgresql.mdx
- v2/emailpassword/pre-built-ui/setup/database-setup/mysql.mdx
- v2/emailpassword/pre-built-ui/setup/database-setup/postgresql.mdx
- v2/passwordless/custom-ui/init/database-setup/mysql.mdx
- v2/passwordless/custom-ui/init/database-setup/postgresql.mdx
- v2/passwordless/pre-built-ui/setup/database-setup/mysql.mdx
- v2/passwordless/pre-built-ui/setup/database-setup/postgresql.mdx
- v2/session/quick-setup/database-setup/mysql.mdx
- v2/session/quick-setup/database-setup/postgresql.mdx
- v2/thirdparty/custom-ui/init/database-setup/mysql.mdx
- v2/thirdparty/custom-ui/init/database-setup/postgresql.mdx
- v2/thirdparty/pre-built-ui/setup/database-setup/mysql.mdx
- v2/thirdparty/pre-built-ui/setup/database-setup/postgresql.mdx
- v2/thirdpartyemailpassword/custom-ui/init/database-setup/mysql.mdx
- v2/thirdpartyemailpassword/custom-ui/init/database-setup/postgresql.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/database-setup/mysql.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/database-setup/postgresql.mdx
- v2/thirdpartypasswordless/custom-ui/init/database-setup/mysql.mdx
- v2/thirdpartypasswordless/custom-ui/init/database-setup/postgresql.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/database-setup/mysql.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/database-setup/postgresql.mdx
> fix: account linking db schema for postgres and mysql

- v2/emailpassword/advanced-customizations/user-context/custom-request-properties.mdx
- v2/emailpassword/common-customizations/sessions/anonymous-session.mdx
- v2/passwordless/advanced-customizations/user-context/custom-request-properties.mdx
- v2/passwordless/common-customizations/sessions/anonymous-session.mdx
- v2/session/advanced-customizations/user-context/custom-request-properties.mdx
- v2/session/common-customizations/sessions/anonymous-session.mdx
- v2/thirdparty/advanced-customizations/user-context/custom-request-properties.mdx
- v2/thirdparty/common-customizations/sessions/anonymous-session.mdx
- v2/thirdpartyemailpassword/advanced-customizations/user-context/custom-request-properties.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/anonymous-session.mdx
- v2/thirdpartypasswordless/advanced-customizations/user-context/custom-request-properties.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/anonymous-session.mdx
Replaced all occurrences of "triggerred" with "triggered".
> Remove second extra "r" in "triggered"

- v2/emailpassword/nextjs/app-directory/setting-up-backend.mdx
- v2/emailpassword/nextjs/app-directory/setting-up-frontend.mdx
- v2/passwordless/nextjs/app-directory/setting-up-backend.mdx
- v2/passwordless/nextjs/app-directory/setting-up-frontend.mdx
- v2/thirdparty/nextjs/app-directory/setting-up-backend.mdx
- v2/thirdparty/nextjs/app-directory/setting-up-frontend.mdx
- v2/thirdpartyemailpassword/nextjs/app-directory/setting-up-backend.mdx
- v2/thirdpartyemailpassword/nextjs/app-directory/setting-up-frontend.mdx
- v2/thirdpartypasswordless/nextjs/app-directory/setting-up-backend.mdx
- v2/thirdpartypasswordless/nextjs/app-directory/setting-up-frontend.mdx
In App Router, the correct way to create a catch-all segment is through `[[...segmentName]]/page.tsx`, as you can no longer use dynamic routing on the leaf of directories. [Supertokens' app directory example](https://github.com/supertokens/next.js/blob/canary/examples/with-supertokens/app/auth/%5B%5B...path%5D%5D/page.tsx) is correct. 
Seems like the example was also super new, documentation typo, I presume. 
- https://github.com/supertokens/next.js/commit/9e7d2d011121dd6fa90c491c9e81ee7c7552b710#diff-401e3d26e1b3958c21cd08b9146e1e9cc9f4db8652c259644b96693e433217f5
> Fix incorrect instructions for Next.js app router

- v2/src/theme/TOC/styles.module.css
Fixes webpack css ruleset warning in development.
> fix: webpack css ruleset warning.

- v2/emailpassword/advanced-customizations/frontend-hooks/redirection-callback.mdx
- v2/emailpassword/common-customizations/embed-sign-in-up-form.mdx
- v2/emailpassword/pre-built-ui/auth-redirection.mdx
- v2/passwordless/advanced-customizations/frontend-hooks/redirection-callback.mdx
- v2/passwordless/common-customizations/embed-sign-in-up-form.mdx
- v2/passwordless/common-customizations/styling/changing-style.mdx
- v2/passwordless/pre-built-ui/auth-redirection.mdx
- v2/passwordless/pre-built-ui/further-reading/passwordless-login.mdx
- v2/src/plugins/codeTypeChecking/jsEnv/package.json
- v2/thirdparty/advanced-customizations/frontend-hooks/redirection-callback.mdx
- v2/thirdparty/common-customizations/embed-sign-in-up-form.mdx
- v2/thirdparty/pre-built-ui/auth-redirection.mdx
- v2/thirdpartyemailpassword/advanced-customizations/frontend-hooks/redirection-callback.mdx
- v2/thirdpartyemailpassword/common-customizations/embed-sign-in-up-form.mdx
- v2/thirdpartyemailpassword/pre-built-ui/auth-redirection.mdx
- v2/thirdpartypasswordless/advanced-customizations/frontend-hooks/redirection-callback.mdx
- v2/thirdpartypasswordless/common-customizations/embed-sign-in-up-form.mdx
- v2/thirdpartypasswordless/common-customizations/styling/changing-style.mdx
- v2/thirdpartypasswordless/pre-built-ui/auth-redirection.mdx
- v2/thirdpartypasswordless/pre-built-ui/further-reading/passwordless-login.mdx
This PR updates the docs to reflect changes from https://github.com/supertokens/supertokens-auth-react/pull/766 PR.
> feat: Add getRedirectionURL docs

- v2/src/components/recipeBoxes/add_ons.tsx
- v2/src/components/recipeBoxes/authMode.tsx
- v2/src/components/recipeBoxes/refs.tsx
Using normal JS variables in the place react state to store the icons paths.
The reason why the flicker was happening in the first place is that the src url for the image tag is provided on the client side some time after rendering the html.
So last week we have fixed missing/duplicate alt attribute to images so that's when this bug got introduced. Since before that there were no alt tags this behaviour never observed.
Previous build `guides.html` output
after fix 
> fix: guides page images rendering issue

- v2/emailpassword/common-customizations/sessions/claims/claim-validators.mdx
- v2/passwordless/common-customizations/sessions/claims/claim-validators.mdx
- v2/session/common-customizations/sessions/claims/claim-validators.mdx
- v2/src/plugins/codeTypeChecking/jsEnv/package.json
- v2/thirdparty/common-customizations/sessions/claims/claim-validators.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/claims/claim-validators.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/claims/claim-validators.mdx
Add docs for using DateProvider in SessionClaimValidator
- https://github.com/supertokens/supertokens-website/pull/241
> feat: Add docs for using DateProvider in SessionClaimValidator

- v2/emailpassword/custom-ui/init/user-management-dashboard/setup.mdx
- v2/emailpassword/pre-built-ui/setup/user-management-dashboard/setup.mdx
- v2/passwordless/custom-ui/init/user-management-dashboard/setup.mdx
- v2/passwordless/pre-built-ui/setup/user-management-dashboard/setup.mdx
- v2/thirdparty/custom-ui/init/user-management-dashboard/setup.mdx
- v2/thirdparty/pre-built-ui/setup/user-management-dashboard/setup.mdx
- v2/thirdpartyemailpassword/custom-ui/init/user-management-dashboard/setup.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/user-management-dashboard/setup.mdx
- v2/thirdpartypasswordless/custom-ui/init/user-management-dashboard/setup.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/user-management-dashboard/setup.mdx
- v2/userdashboard/about.mdx
Based on user feedback, I have added an admonition to specify the location of the dashboard in Next.js vs. other frameworks.
> docs: added admonition clarifying dashboard url

- v2/emailpassword/common-customizations/get-user-info.mdx
- v2/passwordless/common-customizations/get-user-info.mdx
- v2/thirdparty/common-customizations/get-user-info.mdx
- v2/thirdpartyemailpassword/common-customizations/get-user-info.mdx
- v2/thirdpartypasswordless/common-customizations/get-user-info.mdx
On this page (https://supertokens.com/docs/passwordless/common-customizations/get-user-info#fetching-information-using-the-users-email), fixed text references to getUserByEmail, getUserById in text around node-related snippets since those are not being used in the code snippets.
I used COPY SECTION since there was a lot of duplication among all recipes, which I believe made this slip by.
> fix: inaccurate text references in nodejs snippets

- v2/src/css/custom.css
- v2/src/theme/Tabs/index.js
Change the name of the tabs-container class to docs-tabs-container for tabs to prevent conflicts with the SaaS dashboard CSS introduced with this PR: https://github.com/supertokens/main-website/pull/1239
The above PR added the SaaS dashboard CSS to all the pages which also had a `tabs-container` class which apart from a few other things set the width to 60vw as shown in the below screenshot:
This PR resolves that by removing the conflict in class name.
N/A
N/A
> fix: Tabs taking full width in docs

- v2/mfa/backend-setup.mdx
- v2/mfa/email-sms-otp/otp-for-all-users.mdx
- v2/mfa/email-sms-otp/otp-for-opt-in-users.mdx
- v2/mfa/frontend-setup.mdx
- v2/mfa/step-up-auth.mdx
- v2/mfa/totp/totp-for-all-users.mdx
- v2/mfa/totp/totp-for-opt-in-users.mdx
This PR changes the string values for MFA factors to instead use the `MultiFactorAuth.FactorIds` object.
Closes https://github.com/supertokens/supertokens-node/issues/830
> refactor: use ENUM values for MFA factors

- v2/thirdparty/common-customizations/sign-in-and-up/custom-providers.mdx
- v2/thirdpartyemailpassword/common-customizations/signup-form/custom-providers.mdx
- v2/thirdpartypasswordless/common-customizations/signup-form/custom-providers.mdx
> fix: python custom provider override snippet

- v2/thirdparty/common-customizations/sign-in-and-up/custom-providers.mdx
- v2/thirdpartyemailpassword/common-customizations/signup-form/custom-providers.mdx
- v2/thirdpartypasswordless/common-customizations/signup-form/custom-providers.mdx
> fix: unused import

- v2/emailpassword/nestjs/guide.mdx
- v2/passwordless/nestjs/guide.mdx
- v2/thirdparty/nestjs/guide.mdx
- v2/thirdpartyemailpassword/nestjs/guide.mdx
- v2/thirdpartypasswordless/nestjs/guide.mdx
This PR updates the NestJS AuthGuard to use `getSession` instead of `verifySession`.
> fix: Update NestJS AuthGuard to use getSession

- v2/community/supertokens-core/self-hosted/self-hosted-with-aws.mdx
- v2/emailpassword/custom-ui/init/core/self-hosted-with-aws.mdx
- v2/emailpassword/pre-built-ui/setup/core/self-hosted-with-aws.mdx
- v2/emailpassword/quick-setup/core/self-hosted-with-aws.mdx
- v2/emailpassword/sidebars.js
- v2/passwordless/custom-ui/init/core/self-hosted-with-aws.mdx
- v2/passwordless/pre-built-ui/setup/core/self-hosted-with-aws.mdx
- v2/passwordless/sidebars.js
- v2/session/quick-setup/core/self-hosted-with-aws.mdx
- v2/session/sidebars.js
- v2/thirdparty/custom-ui/init/core/self-hosted-with-aws.mdx
- v2/thirdparty/pre-built-ui/setup/core/self-hosted-with-aws.mdx
- v2/thirdparty/sidebars.js
- v2/thirdpartyemailpassword/custom-ui/init/core/self-hosted-with-aws.mdx
- v2/thirdpartyemailpassword/pre-built-ui/setup/core/self-hosted-with-aws.mdx
- v2/thirdpartyemailpassword/sidebars.js
- v2/thirdpartypasswordless/custom-ui/init/core/self-hosted-with-aws.mdx
- v2/thirdpartypasswordless/pre-built-ui/setup/core/self-hosted-with-aws.mdx
- v2/thirdpartypasswordless/sidebars.js
We're fans of Supertokens and added support to install it on AWS using stacksnap 
- N/A
> Added a self hosting option for AWS

- v2/emailpassword/nextjs/app-directory/protecting-route.mdx
- v2/emailpassword/nextjs/app-directory/server-components-requests.mdx
- v2/emailpassword/nextjs/session-verification/in-ssr.mdx
- v2/passwordless/nextjs/app-directory/protecting-route.mdx
- v2/passwordless/nextjs/app-directory/server-components-requests.mdx
- v2/passwordless/nextjs/session-verification/in-ssr.mdx
- v2/thirdparty/common-customizations/account-linking/automatic-account-linking.mdx
- v2/thirdparty/nextjs/app-directory/protecting-route.mdx
- v2/thirdparty/nextjs/app-directory/server-components-requests.mdx
- v2/thirdparty/nextjs/session-verification/in-ssr.mdx
- v2/thirdpartyemailpassword/nextjs/app-directory/protecting-route.mdx
- v2/thirdpartyemailpassword/nextjs/app-directory/server-components-requests.mdx
- v2/thirdpartyemailpassword/nextjs/session-verification/in-ssr.mdx
- v2/thirdpartypasswordless/common-customizations/account-linking/automatic-account-linking.mdx
- v2/thirdpartypasswordless/nextjs/app-directory/protecting-route.mdx
- v2/thirdpartypasswordless/nextjs/app-directory/server-components-requests.mdx
- v2/thirdpartypasswordless/nextjs/session-verification/in-ssr.mdx
This PR removes getSession usage from SSR. 
> fix: Remove getSession usage from SSR

- v2/emailpassword/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/emailpassword/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/passwordless/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/passwordless/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/session/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/session/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/thirdparty/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/thirdparty/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/share-session-across-sub-domains.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/multiple-api-endpoints.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/share-session-across-sub-domains.mdx
We found that browsers don't add a leading dot if `sessionTokenFrontendDomain` lacks one, preventing cookies from being shared across subdomains. To ensure consistency, we now add a leading dot to all cookie domain configurations by default.
> fix: Add a leading dot while setting the cookie domain

- v2/src/components/httpNetworking.ts
- v2/src/components/utils.ts
- v2/src/theme/Layout/index.js
Send sdk logs to the server when auth error occurs (either front_token_removed or auth_error).
Override the native console implementation
> Chore: Send logs

- v2/thirdparty/common-customizations/deduplication/implementing-deduplication.mdx
- v2/thirdpartyemailpassword/common-customizations/deduplication/implementing-deduplication.mdx
- v2/thirdpartypasswordless/common-customizations/deduplication/implementing-deduplication.mdx
If we don't check the error is nil, the code will panic if there's no error in it.
```
2024/07/06 21:10:34 [Recovery] 2024/07/06 - 21:10:34 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:261 (0x100495407)
panicmem: panic(memoryError)
/usr/local/go/src/runtime/signal_unix.go:881 (0x1004953d4)
sigpanic: panicmem()
/Users/da/github/xxx/server/supertokens.go:161 (0x100d09604)
InitSuperToken.thirdPartyAPIOverride.func3.1: if err.Error() == "Cannot sign up as email already exists" {
/Users/da/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.22.0/recipe/thirdparty/api/signinup.go:82 (0x100bc09bb)
SignInUpAPI: result, err := (*apiImplementation.SignInUpPOST)(provider, input, tenantId, options, userContext) …
```
> fix: Resolve the potential panic error in the Go version example in implementing-deduplication.mdx.

- v2/emailpassword/common-customizations/sessions/with-jwt/jwt-verification.mdx
- v2/passwordless/common-customizations/sessions/with-jwt/jwt-verification.mdx
- v2/session/common-customizations/sessions/with-jwt/jwt-verification.mdx
- v2/src/components/tabs/BackendSDKTabs.tsx
- v2/thirdparty/common-customizations/sessions/with-jwt/jwt-verification.mdx
- v2/thirdpartyemailpassword/common-customizations/sessions/with-jwt/jwt-verification.mdx
- v2/thirdpartypasswordless/common-customizations/sessions/with-jwt/jwt-verification.mdx
Adds Java example to JWT verification.
- https://github.com/supertokens/docs/issues/5 - Final checkbox. Only adds Java examples
> Add java examples to jwt-verification.

- v2/emailpassword/advanced-customizations/backend-sdk-core-interceptor.mdx
- v2/passwordless/advanced-customizations/backend-sdk-core-interceptor.mdx
- v2/session/advanced-customizations/backend-sdk-core-interceptor.mdx
- v2/src/plugins/codeTypeChecking/goEnv/go.mod
- v2/src/plugins/codeTypeChecking/goEnv/go.sum
- v2/src/plugins/codeTypeChecking/jsEnv/package.json
- v2/thirdparty/advanced-customizations/backend-sdk-core-interceptor.mdx
- v2/thirdparty/common-customizations/multi-tenancy/custom-provider.mdx
- v2/thirdparty/common-customizations/multi-tenancy/new-tenant-config.mdx
- v2/thirdparty/common-customizations/sign-in-and-up/custom-providers.mdx
- v2/thirdparty/common-customizations/sign-in-and-up/provider-config.mdx
- v2/thirdparty/custom-ui/multitenant-login.mdx
- v2/thirdparty/pre-built-ui/multitenant-login.mdx
- v2/thirdpartyemailpassword/advanced-customizations/backend-sdk-core-interceptor.mdx
- v2/thirdpartyemailpassword/common-customizations/multi-tenancy/custom-provider.mdx
- v2/thirdpartyemailpassword/common-customizations/multi-tenancy/new-tenant-config.mdx
- v2/thirdpartyemailpassword/common-customizations/sign-in-and-up/provider-config.mdx
- v2/thirdpartyemailpassword/common-customizations/signup-form/custom-providers.mdx
- v2/thirdpartyemailpassword/custom-ui/multitenant-login.mdx
- v2/thirdpartyemailpassword/pre-built-ui/multitenant-login.mdx
- v2/thirdpartypasswordless/advanced-customizations/backend-sdk-core-interceptor.mdx
- v2/thirdpartypasswordless/common-customizations/multi-tenancy/custom-provider.mdx
- v2/thirdpartypasswordless/common-customizations/multi-tenancy/new-tenant-config.mdx
- v2/thirdpartypasswordless/common-customizations/sign-in-and-up/provider-config.mdx
- v2/thirdpartypasswordless/common-customizations/signup-form/custom-providers.mdx
- v2/thirdpartypasswordless/custom-ui/multitenant-login.mdx
- v2/thirdpartypasswordless/pre-built-ui/multitenant-login.mdx
> fix: oidc urls and golang type fix

- v2/emailpassword/common-customizations/email-verification/changing-style.mdx
- v2/emailpassword/common-customizations/styling/changing-style.mdx
- v2/passwordless/common-customizations/email-verification/changing-style.mdx
- v2/passwordless/common-customizations/styling/changing-style.mdx
- v2/thirdparty/common-customizations/email-verification/changing-style.mdx
- v2/thirdparty/common-customizations/styling/changing-style.mdx
- v2/thirdpartyemailpassword/common-customizations/email-verification/changing-style.mdx
- v2/thirdpartyemailpassword/common-customizations/styling/changing-style.mdx
- v2/thirdpartypasswordless/common-customizations/email-verification/changing-style.mdx
- v2/thirdpartypasswordless/common-customizations/styling/changing-style.mdx
docs: remove references to Rubik and font loading
- https://github.com/supertokens/supertokens-auth-react/pull/840
> docs: remove references to Rubik and font loading

- v2/package-lock.json
- v2/package.json
- v2/src/css/custom.css
- v2/src/theme/SearchBar/index.js
- v2/yarn.lock
The alpha version of @docsearch/react is unstable. This has been updated to a more stable version
https://www.loom.com/share/1d09115fff904bfeb5549227a27f6703
Update all Beta + Alpha dependencies
> Use stable version of @docsearch/react

- v2/src/components/appInfoForm/index.tsx
- v2/src/components/appInfoForm/style.css
CSS style with "!important' is overriding the default style of a text.
Enforce white text color for .nextjs-api-route-text using !important
- Manual test
> Fix: poor contrast in text

- v2/attackprotectionsuite/backend-setup.mdx
- v2/emailpassword/advanced-customizations/apis-override/custom-response/general-error.mdx
- v2/emailpassword/common-customizations/handling-signup-success.mdx
- v2/emailpassword/common-customizations/username-password/emailpassword-changes.mdx
- v2/emailpassword/migration/account-creation/ep-migration-without-password-hash.mdx
- v2/src/plugins/codeTypeChecking/goEnv/go.mod
- v2/src/plugins/codeTypeChecking/goEnv/go.sum
- v2/src/plugins/codeTypeChecking/pythonEnv/requirements.txt
- v2/thirdpartyemailpassword/advanced-customizations/apis-override/custom-response/general-error.mdx
- v2/thirdpartyemailpassword/common-customizations/handling-signinup-success.mdx
- v2/thirdpartyemailpassword/migration/account-creation/ep-migration-without-password-hash.mdx
This PR adds type related fixes to fix breaking changes in the docs after form field type changes for supporting any type in value. This addresses the changes for go and python.
> feat: Update all go/python docs with type fixes regarding form field values

- v2/emailpassword/nestjs/guide.mdx
- v2/passwordless/nestjs/guide.mdx
- v2/thirdparty/nestjs/guide.mdx
- v2/thirdpartyemailpassword/nestjs/guide.mdx
- v2/thirdpartypasswordless/nestjs/guide.mdx
fix typo in nestjs integration guide
- Slack [convo](https://supertokens.slack.com/archives/D02B887A2MQ/p1726241992568029)
> fix typo in nestjs integration guide

- v2/emailpassword/troubleshooting/how-to-troubleshoot.mdx
- v2/passwordless/troubleshooting/how-to-troubleshoot.mdx
- v2/session/troubleshooting/how-to-troubleshoot.mdx
- v2/src/plugins/codeTypeChecking/dart_env/pubspec.lock
- v2/src/plugins/codeTypeChecking/dart_env/pubspec.yaml
- v2/thirdparty/troubleshooting/how-to-troubleshoot.mdx
- v2/thirdpartyemailpassword/troubleshooting/how-to-troubleshoot.mdx
- v2/thirdpartypasswordless/troubleshooting/how-to-troubleshoot.mdx
Updates the flutter SDK version to ensure that the docs pass code type check for `dart`.
> fix: bump flutter SDK version based on updated docs

- v3/docs/multi-tenancy/delete-app.mdx
https://deploy-preview-904--starlit-elf-06ee1a.netlify.app/docs/multi-tenancy/delete-app
Fixes https://github.com/supertokens/docs/issues/892
This PR adds documentation explaining how to delete an app in a multi-tenant setup.
Key additions:
- New file `docs/multi-tenancy/delete-app.mdx`
- Documents the requirements for app deletion:
- Request must come from public app and tenant
- App must not have any non-public tenants
- Includes cURL example for the deletion API endpoint
- Added relevant warnings about the irreversible nature of deletion
This complements the existing app creation documentation and provides users with the complete lifecycle management of apps in SuperTokens.
> docs: Add documentation for app deletion in multi-tenancy

- v3/src/components/Forms/ExampleAppForm.tsx
Updates the auto-generated value when selected `Go` as the backend, to match the value required in the `npx create-supertokens-app` command on https://supertokens.com/docs/quickstart/example-apps/generate-example-app.
After generating with the existing value for Go (`go`), the following error occurs on running the command:
Example command: 
```
npx create-supertokens-app --appname=example --recipe=emailpassword --frontend=vue --backend=go
```
Re-running after changing `go` to `go-http` fixes the issue on the command, so this change updates the form to reflect this.
ie.
```
npx create-supertokens-app --appname=example --recipe=emailpassword --frontend=vue --backend=go-http
```
> Fix Go option on example app generation form

- docs/platform-configuration/email-delivery.mdx
- docs/platform-configuration/sms-delivery.mdx
This PR adds some details about error handling in custom sendEmail and sendSMS methods and encourages to throw errors so that they are handled accordingly.
**[Link to change](https://docs-git-feat-add-error-handling-details-in-5a85e8-supertokens.vercel.app/docs/platform-configuration/email-delivery#custom-method)**
> feat: add error handling details in custom send email method

- docs/quickstart/integrations/aws-lambda/quickstart-guide.mdx
This PR adds details about using plugins with AWS lambda and how to filter and not pass them to SuperTokens.
**[Link to change](https://docs-git-feat-add-details-about-aws-lambda-plugins-supertokens.vercel.app/docs/quickstart/integrations/aws-lambda/quickstart-guide#using-with-aws-lambda-plugins--extensions)**
> feat: add details about aws lambda plugins

- docs/deployment/self-host-supertokens.mdx
This PR updates the self hosted docs to indicate the necessity to use the correct postgresql scheme designator. This issue was reported on [discord](https://discord.com/channels/603466164219281420/1224328457589227540/threads/1360701880522510346)
> feat: Add caution about postgres scheme designator in self hosted doc
